// Package envoy provides bootstrap configuration generation for Envoy proxy
package envoy

import (
	"fmt"
	"os"
	"path/filepath"
	"text/template"
)

// BootstrapConfig holds configuration for generating Envoy bootstrap
type BootstrapConfig struct {
	// Admin interface
	AdminPort int

	// Listeners
	HTTPListenPort  int
	HTTPSListenPort int
	HTTP3ListenPort int // QUIC - EXPERIMENTAL

	// External Authorization
	ExtAuthzHost string
	ExtAuthzPort int

	// xDS Control Plane
	XDSServerAddr string
	XDSNodeID     string
	XDSCluster    string

	// TLS Interception
	TLSInterceptEnabled bool
	TLSCACertPath       string
	TLSCAKeyPath        string

	// Feature flags
	HTTP3Enabled bool // EXPERIMENTAL
	AccessLog    bool
	Tracing      bool
}

// DefaultBootstrapConfig returns a BootstrapConfig with sensible defaults
func DefaultBootstrapConfig() BootstrapConfig {
	return BootstrapConfig{
		AdminPort:           9901,
		HTTPListenPort:      10000,
		HTTPSListenPort:     10443,
		HTTP3ListenPort:     10443, // QUIC uses same port as HTTPS
		ExtAuthzHost:        "127.0.0.1",
		ExtAuthzPort:        9002,
		XDSServerAddr:       "api-server:18000",
		XDSNodeID:           "egress-node",
		XDSCluster:          "marchproxy-egress-cluster",
		TLSInterceptEnabled: false,
		HTTP3Enabled:        false, // EXPERIMENTAL - disabled by default
		AccessLog:           true,
		Tracing:             false,
	}
}

// GenerateBootstrap generates an Envoy bootstrap configuration file
func GenerateBootstrap(cfg BootstrapConfig, outputPath string) error {
	// Ensure directory exists
	dir := filepath.Dir(outputPath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create directory %s: %w", dir, err)
	}

	// Parse and execute template
	tmpl, err := template.New("bootstrap").Parse(bootstrapTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse template: %w", err)
	}

	file, err := os.Create(outputPath)
	if err != nil {
		return fmt.Errorf("failed to create file %s: %w", outputPath, err)
	}
	defer file.Close()

	if err := tmpl.Execute(file, cfg); err != nil {
		return fmt.Errorf("failed to execute template: %w", err)
	}

	return nil
}

// bootstrapTemplate is the Envoy bootstrap configuration template
const bootstrapTemplate = `# MarchProxy Egress - Envoy Bootstrap Configuration
# Generated by proxy-egress bootstrap generator
# WARNING: HTTP/3 (QUIC) support is EXPERIMENTAL

admin:
  address:
    socket_address:
      address: 0.0.0.0
      port_value: {{.AdminPort}}

node:
  id: {{.XDSNodeID}}
  cluster: {{.XDSCluster}}

static_resources:
  listeners:
    # HTTP/1.1 and HTTP/2 Listener
    - name: egress_http_listener
      address:
        socket_address:
          address: 0.0.0.0
          port_value: {{.HTTPListenPort}}
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: egress_http
                codec_type: AUTO
                {{- if .AccessLog}}
                access_log:
                  - name: envoy.access_loggers.stdout
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
                      log_format:
                        json_format:
                          timestamp: "%START_TIME%"
                          client_ip: "%DOWNSTREAM_REMOTE_ADDRESS_WITHOUT_PORT%"
                          method: "%REQ(:METHOD)%"
                          path: "%REQ(:PATH)%"
                          host: "%REQ(:AUTHORITY)%"
                          protocol: "%PROTOCOL%"
                          response_code: "%RESPONSE_CODE%"
                          response_flags: "%RESPONSE_FLAGS%"
                          bytes_sent: "%BYTES_SENT%"
                          duration_ms: "%DURATION%"
                          upstream_host: "%UPSTREAM_HOST%"
                          user_agent: "%REQ(USER-AGENT)%"
                {{- end}}
                http_filters:
                  # External Authorization filter for threat intelligence
                  - name: envoy.filters.http.ext_authz
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
                      transport_api_version: V3
                      grpc_service:
                        envoy_grpc:
                          cluster_name: ext_authz_cluster
                        timeout: 0.1s
                      failure_mode_allow: false
                      with_request_body:
                        max_request_bytes: 8192
                        allow_partial_message: true
                        pack_as_bytes: true
                      status_on_error:
                        code: ServiceUnavailable
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
                route_config:
                  name: egress_route
                  virtual_hosts:
                    - name: egress_service
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: dynamic_forward_proxy_cluster
                            timeout: 30s

    # HTTPS Listener with TLS termination
    - name: egress_https_listener
      address:
        socket_address:
          address: 0.0.0.0
          port_value: {{.HTTPSListenPort}}
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: egress_https
                codec_type: AUTO
                http2_protocol_options:
                  max_concurrent_streams: 100
                  initial_stream_window_size: 65536
                  initial_connection_window_size: 1048576
                {{- if .AccessLog}}
                access_log:
                  - name: envoy.access_loggers.stdout
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
                {{- end}}
                http_filters:
                  - name: envoy.filters.http.ext_authz
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
                      transport_api_version: V3
                      grpc_service:
                        envoy_grpc:
                          cluster_name: ext_authz_cluster
                        timeout: 0.1s
                      failure_mode_allow: false
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
                route_config:
                  name: egress_https_route
                  virtual_hosts:
                    - name: egress_https_service
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: dynamic_forward_proxy_cluster
                            timeout: 30s
{{if .HTTP3Enabled}}
    # HTTP/3 (QUIC) Listener - EXPERIMENTAL
    # WARNING: This feature is experimental and may not be stable
    - name: egress_http3_listener
      address:
        socket_address:
          protocol: UDP
          address: 0.0.0.0
          port_value: {{.HTTP3ListenPort}}
      udp_listener_config:
        quic_options: {}
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: egress_http3
                codec_type: HTTP3
                http3_protocol_options:
                  quic_protocol_options:
                    max_concurrent_streams: 100
                    initial_stream_window_size: 65536
                {{- if .AccessLog}}
                access_log:
                  - name: envoy.access_loggers.stdout
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
                {{- end}}
                http_filters:
                  - name: envoy.filters.http.ext_authz
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
                      transport_api_version: V3
                      grpc_service:
                        envoy_grpc:
                          cluster_name: ext_authz_cluster
                        timeout: 0.1s
                      failure_mode_allow: false
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
                route_config:
                  name: egress_http3_route
                  virtual_hosts:
                    - name: egress_http3_service
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: dynamic_forward_proxy_cluster
                            timeout: 30s
{{end}}
  clusters:
    # External Authorization cluster (Go ext_authz server)
    - name: ext_authz_cluster
      type: STATIC
      connect_timeout: 0.25s
      typed_extension_protocol_options:
        envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
          "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
          explicit_http_config:
            http2_protocol_options: {}
      load_assignment:
        cluster_name: ext_authz_cluster
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: {{.ExtAuthzHost}}
                      port_value: {{.ExtAuthzPort}}

    # Dynamic forward proxy cluster for egress
    - name: dynamic_forward_proxy_cluster
      type: LOGICAL_DNS
      connect_timeout: 5s
      dns_lookup_family: V4_ONLY
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: dynamic_forward_proxy_cluster
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 0.0.0.0
                      port_value: 443

    # xDS Control Plane cluster
    - name: xds_cluster
      type: STRICT_DNS
      connect_timeout: 5s
      typed_extension_protocol_options:
        envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
          "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
          explicit_http_config:
            http2_protocol_options: {}
      load_assignment:
        cluster_name: xds_cluster
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: {{.XDSServerAddr}}
                      port_value: 18000

# Dynamic configuration via xDS (optional)
# Uncomment to enable dynamic configuration from control plane
# dynamic_resources:
#   lds_config:
#     resource_api_version: V3
#     api_config_source:
#       api_type: GRPC
#       transport_api_version: V3
#       grpc_services:
#         - envoy_grpc:
#             cluster_name: xds_cluster
#   cds_config:
#     resource_api_version: V3
#     api_config_source:
#       api_type: GRPC
#       transport_api_version: V3
#       grpc_services:
#         - envoy_grpc:
#             cluster_name: xds_cluster

layered_runtime:
  layers:
    - name: static_layer_0
      static_layer:
        envoy:
          resource_limits:
            listener:
              egress_http_listener:
                connection_limit: 50000
              egress_https_listener:
                connection_limit: 50000
        overload:
          global_downstream_max_connections: 100000
`

// GenerateStaticConfig generates a static Envoy configuration (no xDS)
func GenerateStaticConfig(cfg BootstrapConfig, outputPath string) error {
	return GenerateBootstrap(cfg, outputPath)
}
