# Beta environment overrides (dal2 cluster)
namespace: marchproxy
imagePullSecrets:
  - name: ghcr-pull-secret
replicaCount: 2
image:
  registry: ghcr.io/penguintechinc/marchproxy
  pullPolicy: Always
env:
  LOG_LEVEL: INFO
  RELEASE_MODE: "false"
ingress:
  hosts:
    - host: marchproxy.penguintech.cloud
  tls:
    - secretName: penguintech-wildcard-tls
      hosts:
        - marchproxy.penguintech.cloud
