// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: marchproxy/media.proto

package marchproxy

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MediaService_GetCapabilities_FullMethodName           = "/marchproxy.MediaService/GetCapabilities"
	MediaService_GetEffectiveLimits_FullMethodName        = "/marchproxy.MediaService/GetEffectiveLimits"
	MediaService_UpdatePolicy_FullMethodName              = "/marchproxy.MediaService/UpdatePolicy"
	MediaService_GetPolicy_FullMethodName                 = "/marchproxy.MediaService/GetPolicy"
	MediaService_ListStreams_FullMethodName               = "/marchproxy.MediaService/ListStreams"
	MediaService_GetStream_FullMethodName                 = "/marchproxy.MediaService/GetStream"
	MediaService_StopStream_FullMethodName                = "/marchproxy.MediaService/StopStream"
	MediaService_GetStreamStats_FullMethodName            = "/marchproxy.MediaService/GetStreamStats"
	MediaService_GetBitrateProfiles_FullMethodName        = "/marchproxy.MediaService/GetBitrateProfiles"
	MediaService_SetBitrateProfiles_FullMethodName        = "/marchproxy.MediaService/SetBitrateProfiles"
	MediaService_AddRestreamDestination_FullMethodName    = "/marchproxy.MediaService/AddRestreamDestination"
	MediaService_RemoveRestreamDestination_FullMethodName = "/marchproxy.MediaService/RemoveRestreamDestination"
	MediaService_ListRestreamDestinations_FullMethodName  = "/marchproxy.MediaService/ListRestreamDestinations"
	MediaService_StartRestream_FullMethodName             = "/marchproxy.MediaService/StartRestream"
	MediaService_StopRestream_FullMethodName              = "/marchproxy.MediaService/StopRestream"
	MediaService_GetMediaStats_FullMethodName             = "/marchproxy.MediaService/GetMediaStats"
	MediaService_StreamMediaStats_FullMethodName          = "/marchproxy.MediaService/StreamMediaStats"
)

// MediaServiceClient is the client API for MediaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MediaService provides RTMP/Media module specific operations.
// This extends the base ModuleService with media-specific functionality.
type MediaServiceClient interface {
	// GetCapabilities returns the hardware capabilities of this media instance
	GetCapabilities(ctx context.Context, in *GetCapabilitiesRequest, opts ...grpc.CallOption) (*GetCapabilitiesResponse, error)
	// GetEffectiveLimits returns the effective resolution/bitrate limits
	// considering both hardware capabilities and admin policy
	GetEffectiveLimits(ctx context.Context, in *GetEffectiveLimitsRequest, opts ...grpc.CallOption) (*GetEffectiveLimitsResponse, error)
	// UpdatePolicy updates the media policy from the Manager service
	UpdatePolicy(ctx context.Context, in *UpdatePolicyRequest, opts ...grpc.CallOption) (*UpdatePolicyResponse, error)
	// GetPolicy returns the current media policy
	GetPolicy(ctx context.Context, in *GetPolicyRequest, opts ...grpc.CallOption) (*GetPolicyResponse, error)
	// ListStreams returns all active streams
	ListStreams(ctx context.Context, in *ListStreamsRequest, opts ...grpc.CallOption) (*ListStreamsResponse, error)
	// GetStream returns details of a specific stream
	GetStream(ctx context.Context, in *GetStreamRequest, opts ...grpc.CallOption) (*GetStreamResponse, error)
	// StopStream terminates a specific stream
	StopStream(ctx context.Context, in *StopStreamRequest, opts ...grpc.CallOption) (*StopStreamResponse, error)
	// GetStreamStats returns statistics for a specific stream
	GetStreamStats(ctx context.Context, in *GetStreamStatsRequest, opts ...grpc.CallOption) (*GetStreamStatsResponse, error)
	// GetBitrateProfiles returns configured bitrate profiles
	GetBitrateProfiles(ctx context.Context, in *GetBitrateProfilesRequest, opts ...grpc.CallOption) (*GetBitrateProfilesResponse, error)
	// SetBitrateProfiles configures the transcode ladder
	SetBitrateProfiles(ctx context.Context, in *SetBitrateProfilesRequest, opts ...grpc.CallOption) (*SetBitrateProfilesResponse, error)
	// AddRestreamDestination adds a restream destination (Twitch, YouTube, etc.)
	AddRestreamDestination(ctx context.Context, in *AddRestreamDestinationRequest, opts ...grpc.CallOption) (*AddRestreamDestinationResponse, error)
	// RemoveRestreamDestination removes a restream destination
	RemoveRestreamDestination(ctx context.Context, in *RemoveRestreamDestinationRequest, opts ...grpc.CallOption) (*RemoveRestreamDestinationResponse, error)
	// ListRestreamDestinations lists all configured restream destinations
	ListRestreamDestinations(ctx context.Context, in *ListRestreamDestinationsRequest, opts ...grpc.CallOption) (*ListRestreamDestinationsResponse, error)
	// StartRestream starts restreaming to a destination
	StartRestream(ctx context.Context, in *StartRestreamRequest, opts ...grpc.CallOption) (*StartRestreamResponse, error)
	// StopRestream stops restreaming to a destination
	StopRestream(ctx context.Context, in *StopRestreamRequest, opts ...grpc.CallOption) (*StopRestreamResponse, error)
	// GetMediaStats returns media-specific statistics
	GetMediaStats(ctx context.Context, in *GetMediaStatsRequest, opts ...grpc.CallOption) (*GetMediaStatsResponse, error)
	// StreamMediaStats streams real-time media statistics
	StreamMediaStats(ctx context.Context, in *StreamMediaStatsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamMediaStatsResponse], error)
}

type mediaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMediaServiceClient(cc grpc.ClientConnInterface) MediaServiceClient {
	return &mediaServiceClient{cc}
}

func (c *mediaServiceClient) GetCapabilities(ctx context.Context, in *GetCapabilitiesRequest, opts ...grpc.CallOption) (*GetCapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCapabilitiesResponse)
	err := c.cc.Invoke(ctx, MediaService_GetCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) GetEffectiveLimits(ctx context.Context, in *GetEffectiveLimitsRequest, opts ...grpc.CallOption) (*GetEffectiveLimitsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEffectiveLimitsResponse)
	err := c.cc.Invoke(ctx, MediaService_GetEffectiveLimits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) UpdatePolicy(ctx context.Context, in *UpdatePolicyRequest, opts ...grpc.CallOption) (*UpdatePolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePolicyResponse)
	err := c.cc.Invoke(ctx, MediaService_UpdatePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) GetPolicy(ctx context.Context, in *GetPolicyRequest, opts ...grpc.CallOption) (*GetPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPolicyResponse)
	err := c.cc.Invoke(ctx, MediaService_GetPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) ListStreams(ctx context.Context, in *ListStreamsRequest, opts ...grpc.CallOption) (*ListStreamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStreamsResponse)
	err := c.cc.Invoke(ctx, MediaService_ListStreams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) GetStream(ctx context.Context, in *GetStreamRequest, opts ...grpc.CallOption) (*GetStreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStreamResponse)
	err := c.cc.Invoke(ctx, MediaService_GetStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) StopStream(ctx context.Context, in *StopStreamRequest, opts ...grpc.CallOption) (*StopStreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopStreamResponse)
	err := c.cc.Invoke(ctx, MediaService_StopStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) GetStreamStats(ctx context.Context, in *GetStreamStatsRequest, opts ...grpc.CallOption) (*GetStreamStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStreamStatsResponse)
	err := c.cc.Invoke(ctx, MediaService_GetStreamStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) GetBitrateProfiles(ctx context.Context, in *GetBitrateProfilesRequest, opts ...grpc.CallOption) (*GetBitrateProfilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBitrateProfilesResponse)
	err := c.cc.Invoke(ctx, MediaService_GetBitrateProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) SetBitrateProfiles(ctx context.Context, in *SetBitrateProfilesRequest, opts ...grpc.CallOption) (*SetBitrateProfilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetBitrateProfilesResponse)
	err := c.cc.Invoke(ctx, MediaService_SetBitrateProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) AddRestreamDestination(ctx context.Context, in *AddRestreamDestinationRequest, opts ...grpc.CallOption) (*AddRestreamDestinationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddRestreamDestinationResponse)
	err := c.cc.Invoke(ctx, MediaService_AddRestreamDestination_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) RemoveRestreamDestination(ctx context.Context, in *RemoveRestreamDestinationRequest, opts ...grpc.CallOption) (*RemoveRestreamDestinationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveRestreamDestinationResponse)
	err := c.cc.Invoke(ctx, MediaService_RemoveRestreamDestination_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) ListRestreamDestinations(ctx context.Context, in *ListRestreamDestinationsRequest, opts ...grpc.CallOption) (*ListRestreamDestinationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRestreamDestinationsResponse)
	err := c.cc.Invoke(ctx, MediaService_ListRestreamDestinations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) StartRestream(ctx context.Context, in *StartRestreamRequest, opts ...grpc.CallOption) (*StartRestreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartRestreamResponse)
	err := c.cc.Invoke(ctx, MediaService_StartRestream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) StopRestream(ctx context.Context, in *StopRestreamRequest, opts ...grpc.CallOption) (*StopRestreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopRestreamResponse)
	err := c.cc.Invoke(ctx, MediaService_StopRestream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) GetMediaStats(ctx context.Context, in *GetMediaStatsRequest, opts ...grpc.CallOption) (*GetMediaStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMediaStatsResponse)
	err := c.cc.Invoke(ctx, MediaService_GetMediaStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mediaServiceClient) StreamMediaStats(ctx context.Context, in *StreamMediaStatsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamMediaStatsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MediaService_ServiceDesc.Streams[0], MediaService_StreamMediaStats_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamMediaStatsRequest, StreamMediaStatsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MediaService_StreamMediaStatsClient = grpc.ServerStreamingClient[StreamMediaStatsResponse]

// MediaServiceServer is the server API for MediaService service.
// All implementations must embed UnimplementedMediaServiceServer
// for forward compatibility.
//
// MediaService provides RTMP/Media module specific operations.
// This extends the base ModuleService with media-specific functionality.
type MediaServiceServer interface {
	// GetCapabilities returns the hardware capabilities of this media instance
	GetCapabilities(context.Context, *GetCapabilitiesRequest) (*GetCapabilitiesResponse, error)
	// GetEffectiveLimits returns the effective resolution/bitrate limits
	// considering both hardware capabilities and admin policy
	GetEffectiveLimits(context.Context, *GetEffectiveLimitsRequest) (*GetEffectiveLimitsResponse, error)
	// UpdatePolicy updates the media policy from the Manager service
	UpdatePolicy(context.Context, *UpdatePolicyRequest) (*UpdatePolicyResponse, error)
	// GetPolicy returns the current media policy
	GetPolicy(context.Context, *GetPolicyRequest) (*GetPolicyResponse, error)
	// ListStreams returns all active streams
	ListStreams(context.Context, *ListStreamsRequest) (*ListStreamsResponse, error)
	// GetStream returns details of a specific stream
	GetStream(context.Context, *GetStreamRequest) (*GetStreamResponse, error)
	// StopStream terminates a specific stream
	StopStream(context.Context, *StopStreamRequest) (*StopStreamResponse, error)
	// GetStreamStats returns statistics for a specific stream
	GetStreamStats(context.Context, *GetStreamStatsRequest) (*GetStreamStatsResponse, error)
	// GetBitrateProfiles returns configured bitrate profiles
	GetBitrateProfiles(context.Context, *GetBitrateProfilesRequest) (*GetBitrateProfilesResponse, error)
	// SetBitrateProfiles configures the transcode ladder
	SetBitrateProfiles(context.Context, *SetBitrateProfilesRequest) (*SetBitrateProfilesResponse, error)
	// AddRestreamDestination adds a restream destination (Twitch, YouTube, etc.)
	AddRestreamDestination(context.Context, *AddRestreamDestinationRequest) (*AddRestreamDestinationResponse, error)
	// RemoveRestreamDestination removes a restream destination
	RemoveRestreamDestination(context.Context, *RemoveRestreamDestinationRequest) (*RemoveRestreamDestinationResponse, error)
	// ListRestreamDestinations lists all configured restream destinations
	ListRestreamDestinations(context.Context, *ListRestreamDestinationsRequest) (*ListRestreamDestinationsResponse, error)
	// StartRestream starts restreaming to a destination
	StartRestream(context.Context, *StartRestreamRequest) (*StartRestreamResponse, error)
	// StopRestream stops restreaming to a destination
	StopRestream(context.Context, *StopRestreamRequest) (*StopRestreamResponse, error)
	// GetMediaStats returns media-specific statistics
	GetMediaStats(context.Context, *GetMediaStatsRequest) (*GetMediaStatsResponse, error)
	// StreamMediaStats streams real-time media statistics
	StreamMediaStats(*StreamMediaStatsRequest, grpc.ServerStreamingServer[StreamMediaStatsResponse]) error
	mustEmbedUnimplementedMediaServiceServer()
}

// UnimplementedMediaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMediaServiceServer struct{}

func (UnimplementedMediaServiceServer) GetCapabilities(context.Context, *GetCapabilitiesRequest) (*GetCapabilitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCapabilities not implemented")
}
func (UnimplementedMediaServiceServer) GetEffectiveLimits(context.Context, *GetEffectiveLimitsRequest) (*GetEffectiveLimitsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEffectiveLimits not implemented")
}
func (UnimplementedMediaServiceServer) UpdatePolicy(context.Context, *UpdatePolicyRequest) (*UpdatePolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePolicy not implemented")
}
func (UnimplementedMediaServiceServer) GetPolicy(context.Context, *GetPolicyRequest) (*GetPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPolicy not implemented")
}
func (UnimplementedMediaServiceServer) ListStreams(context.Context, *ListStreamsRequest) (*ListStreamsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListStreams not implemented")
}
func (UnimplementedMediaServiceServer) GetStream(context.Context, *GetStreamRequest) (*GetStreamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStream not implemented")
}
func (UnimplementedMediaServiceServer) StopStream(context.Context, *StopStreamRequest) (*StopStreamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopStream not implemented")
}
func (UnimplementedMediaServiceServer) GetStreamStats(context.Context, *GetStreamStatsRequest) (*GetStreamStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStreamStats not implemented")
}
func (UnimplementedMediaServiceServer) GetBitrateProfiles(context.Context, *GetBitrateProfilesRequest) (*GetBitrateProfilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBitrateProfiles not implemented")
}
func (UnimplementedMediaServiceServer) SetBitrateProfiles(context.Context, *SetBitrateProfilesRequest) (*SetBitrateProfilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetBitrateProfiles not implemented")
}
func (UnimplementedMediaServiceServer) AddRestreamDestination(context.Context, *AddRestreamDestinationRequest) (*AddRestreamDestinationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddRestreamDestination not implemented")
}
func (UnimplementedMediaServiceServer) RemoveRestreamDestination(context.Context, *RemoveRestreamDestinationRequest) (*RemoveRestreamDestinationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveRestreamDestination not implemented")
}
func (UnimplementedMediaServiceServer) ListRestreamDestinations(context.Context, *ListRestreamDestinationsRequest) (*ListRestreamDestinationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRestreamDestinations not implemented")
}
func (UnimplementedMediaServiceServer) StartRestream(context.Context, *StartRestreamRequest) (*StartRestreamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartRestream not implemented")
}
func (UnimplementedMediaServiceServer) StopRestream(context.Context, *StopRestreamRequest) (*StopRestreamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopRestream not implemented")
}
func (UnimplementedMediaServiceServer) GetMediaStats(context.Context, *GetMediaStatsRequest) (*GetMediaStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMediaStats not implemented")
}
func (UnimplementedMediaServiceServer) StreamMediaStats(*StreamMediaStatsRequest, grpc.ServerStreamingServer[StreamMediaStatsResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamMediaStats not implemented")
}
func (UnimplementedMediaServiceServer) mustEmbedUnimplementedMediaServiceServer() {}
func (UnimplementedMediaServiceServer) testEmbeddedByValue()                      {}

// UnsafeMediaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MediaServiceServer will
// result in compilation errors.
type UnsafeMediaServiceServer interface {
	mustEmbedUnimplementedMediaServiceServer()
}

func RegisterMediaServiceServer(s grpc.ServiceRegistrar, srv MediaServiceServer) {
	// If the following call panics, it indicates UnimplementedMediaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MediaService_ServiceDesc, srv)
}

func _MediaService_GetCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).GetCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_GetCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).GetCapabilities(ctx, req.(*GetCapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_GetEffectiveLimits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEffectiveLimitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).GetEffectiveLimits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_GetEffectiveLimits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).GetEffectiveLimits(ctx, req.(*GetEffectiveLimitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_UpdatePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).UpdatePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_UpdatePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).UpdatePolicy(ctx, req.(*UpdatePolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_GetPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).GetPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_GetPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).GetPolicy(ctx, req.(*GetPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_ListStreams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStreamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).ListStreams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_ListStreams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).ListStreams(ctx, req.(*ListStreamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_GetStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).GetStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_GetStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).GetStream(ctx, req.(*GetStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_StopStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).StopStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_StopStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).StopStream(ctx, req.(*StopStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_GetStreamStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStreamStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).GetStreamStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_GetStreamStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).GetStreamStats(ctx, req.(*GetStreamStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_GetBitrateProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBitrateProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).GetBitrateProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_GetBitrateProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).GetBitrateProfiles(ctx, req.(*GetBitrateProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_SetBitrateProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetBitrateProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).SetBitrateProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_SetBitrateProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).SetBitrateProfiles(ctx, req.(*SetBitrateProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_AddRestreamDestination_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRestreamDestinationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).AddRestreamDestination(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_AddRestreamDestination_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).AddRestreamDestination(ctx, req.(*AddRestreamDestinationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_RemoveRestreamDestination_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRestreamDestinationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).RemoveRestreamDestination(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_RemoveRestreamDestination_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).RemoveRestreamDestination(ctx, req.(*RemoveRestreamDestinationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_ListRestreamDestinations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRestreamDestinationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).ListRestreamDestinations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_ListRestreamDestinations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).ListRestreamDestinations(ctx, req.(*ListRestreamDestinationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_StartRestream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRestreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).StartRestream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_StartRestream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).StartRestream(ctx, req.(*StartRestreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_StopRestream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRestreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).StopRestream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_StopRestream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).StopRestream(ctx, req.(*StopRestreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_GetMediaStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMediaStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MediaServiceServer).GetMediaStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MediaService_GetMediaStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MediaServiceServer).GetMediaStats(ctx, req.(*GetMediaStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MediaService_StreamMediaStats_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamMediaStatsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MediaServiceServer).StreamMediaStats(m, &grpc.GenericServerStream[StreamMediaStatsRequest, StreamMediaStatsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MediaService_StreamMediaStatsServer = grpc.ServerStreamingServer[StreamMediaStatsResponse]

// MediaService_ServiceDesc is the grpc.ServiceDesc for MediaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MediaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "marchproxy.MediaService",
	HandlerType: (*MediaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCapabilities",
			Handler:    _MediaService_GetCapabilities_Handler,
		},
		{
			MethodName: "GetEffectiveLimits",
			Handler:    _MediaService_GetEffectiveLimits_Handler,
		},
		{
			MethodName: "UpdatePolicy",
			Handler:    _MediaService_UpdatePolicy_Handler,
		},
		{
			MethodName: "GetPolicy",
			Handler:    _MediaService_GetPolicy_Handler,
		},
		{
			MethodName: "ListStreams",
			Handler:    _MediaService_ListStreams_Handler,
		},
		{
			MethodName: "GetStream",
			Handler:    _MediaService_GetStream_Handler,
		},
		{
			MethodName: "StopStream",
			Handler:    _MediaService_StopStream_Handler,
		},
		{
			MethodName: "GetStreamStats",
			Handler:    _MediaService_GetStreamStats_Handler,
		},
		{
			MethodName: "GetBitrateProfiles",
			Handler:    _MediaService_GetBitrateProfiles_Handler,
		},
		{
			MethodName: "SetBitrateProfiles",
			Handler:    _MediaService_SetBitrateProfiles_Handler,
		},
		{
			MethodName: "AddRestreamDestination",
			Handler:    _MediaService_AddRestreamDestination_Handler,
		},
		{
			MethodName: "RemoveRestreamDestination",
			Handler:    _MediaService_RemoveRestreamDestination_Handler,
		},
		{
			MethodName: "ListRestreamDestinations",
			Handler:    _MediaService_ListRestreamDestinations_Handler,
		},
		{
			MethodName: "StartRestream",
			Handler:    _MediaService_StartRestream_Handler,
		},
		{
			MethodName: "StopRestream",
			Handler:    _MediaService_StopRestream_Handler,
		},
		{
			MethodName: "GetMediaStats",
			Handler:    _MediaService_GetMediaStats_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMediaStats",
			Handler:       _MediaService_StreamMediaStats_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "marchproxy/media.proto",
}
