// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: marchproxy/media.proto

package marchproxy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCapabilitiesRequest) Reset() {
	*x = GetCapabilitiesRequest{}
	mi := &file_marchproxy_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapabilitiesRequest) ProtoMessage() {}

func (x *GetCapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marchproxy_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*GetCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_marchproxy_media_proto_rawDescGZIP(), []int{0}
}

func (x *GetCapabilitiesRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type GetCapabilitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capabilities  *MediaCapabilities     `protobuf:"bytes,1,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	DetectedAt    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=detected_at,json=detectedAt,proto3" json:"detected_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCapabilitiesResponse) Reset() {
	*x = GetCapabilitiesResponse{}
	mi := &file_marchproxy_media_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapabilitiesResponse) ProtoMessage() {}

func (x *GetCapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marchproxy_media_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*GetCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_marchproxy_media_proto_rawDescGZIP(), []int{1}
}

func (x *GetCapabilitiesResponse) GetCapabilities() *MediaCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *GetCapabilitiesResponse) GetDetectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DetectedAt
	}
	return nil
}

type GetEffectiveLimitsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEffectiveLimitsRequest) Reset() {
	*x = GetEffectiveLimitsRequest{}
	mi := &file_marchproxy_media_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEffectiveLimitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEffectiveLimitsRequest) ProtoMessage() {}

func (x *GetEffectiveLimitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marchproxy_media_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEffectiveLimitsRequest.ProtoReflect.Descriptor instead.
func (*GetEffectiveLimitsRequest) Descriptor() ([]byte, []int) {
	return file_marchproxy_media_proto_rawDescGZIP(), []int{2}
}

func (x *GetEffectiveLimitsRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type GetEffectiveLimitsResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	EffectiveMaxResolution  int32                  `protobuf:"varint,1,opt,name=effective_max_resolution,json=effectiveMaxResolution,proto3" json:"effective_max_resolution,omitempty"` // min(hardware, admin)
	EffectiveMaxBitrateKbps int32                  `protobuf:"varint,2,opt,name=effective_max_bitrate_kbps,json=effectiveMaxBitrateKbps,proto3" json:"effective_max_bitrate_kbps,omitempty"`
	HardwareMaxResolution   int32                  `protobuf:"varint,3,opt,name=hardware_max_resolution,json=hardwareMaxResolution,proto3" json:"hardware_max_resolution,omitempty"`
	AdminMaxResolution      *int32                 `protobuf:"varint,4,opt,name=admin_max_resolution,json=adminMaxResolution,proto3,oneof" json:"admin_max_resolution,omitempty"`
	LimitReason             string                 `protobuf:"bytes,5,opt,name=limit_reason,json=limitReason,proto3" json:"limit_reason,omitempty"` // "hardware" or "admin_policy"
	Capabilities            *MediaCapabilities     `protobuf:"bytes,6,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *GetEffectiveLimitsResponse) Reset() {
	*x = GetEffectiveLimitsResponse{}
	mi := &file_marchproxy_media_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEffectiveLimitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEffectiveLimitsResponse) ProtoMessage() {}

func (x *GetEffectiveLimitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marchproxy_media_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEffectiveLimitsResponse.ProtoReflect.Descriptor instead.
func (*GetEffectiveLimitsResponse) Descriptor() ([]byte, []int) {
	return file_marchproxy_media_proto_rawDescGZIP(), []int{3}
}

func (x *GetEffectiveLimitsResponse) GetEffectiveMaxResolution() int32 {
	if x != nil {
		return x.EffectiveMaxResolution
	}
	return 0
}

func (x *GetEffectiveLimitsResponse) GetEffectiveMaxBitrateKbps() int32 {
	if x != nil {
		return x.EffectiveMaxBitrateKbps
	}
	return 0
}

func (x *GetEffectiveLimitsResponse) GetHardwareMaxResolution() int32 {
	if x != nil {
		return x.HardwareMaxResolution
	}
	return 0
}

func (x *GetEffectiveLimitsResponse) GetAdminMaxResolution() int32 {
	if x != nil && x.AdminMaxResolution != nil {
		return *x.AdminMaxResolution
	}
	return 0
}

func (x *GetEffectiveLimitsResponse) GetLimitReason() string {
	if x != nil {
		return x.LimitReason
	}
	return ""
}

func (x *GetEffectiveLimitsResponse) GetCapabilities() *MediaCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type UpdatePolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	PolicyUpdate  *MediaPolicyUpdate     `protobuf:"bytes,2,opt,name=policy_update,json=policyUpdate,proto3" json:"policy_update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePolicyRequest) Reset() {
	*x = UpdatePolicyRequest{}
	mi := &file_marchproxy_media_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePolicyRequest) ProtoMessage() {}

func (x *UpdatePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marchproxy_media_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePolicyRequest.ProtoReflect.Descriptor instead.
func (*UpdatePolicyRequest) Descriptor() ([]byte, []int) {
	return file_marchproxy_media_proto_rawDescGZIP(), []int{4}
}

func (x *UpdatePolicyRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *UpdatePolicyRequest) GetPolicyUpdate() *MediaPolicyUpdate {
	if x != nil {
		return x.PolicyUpdate
	}
	return nil
}

type UpdatePolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AppliedPolicy *MediaPolicy           `protobuf:"bytes,3,opt,name=applied_policy,json=appliedPolicy,proto3" json:"applied_policy,omitempty"`
	Error         *Error                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePolicyResponse) Reset() {
	*x = UpdatePolicyResponse{}
	mi := &file_marchproxy_media_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePolicyResponse) ProtoMessage() {}

func (x *UpdatePolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marchproxy_media_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePolicyResponse.ProtoReflect.Descriptor instead.
func (*UpdatePolicyResponse) Descriptor() ([]byte, []int) {
	return file_marchproxy_media_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePolicyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdatePolicyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdatePolicyResponse) GetAppliedPolicy() *MediaPolicy {
	if x != nil {
		return x.AppliedPolicy
	}
	return nil
}

func (x *UpdatePolicyResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPolicyRequest) Reset() {
	*x = GetPolicyRequest{}
	mi := &file_marchproxy_media_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPolicyRequest) ProtoMessage() {}

func (x *GetPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marchproxy_media_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPolicyRequest.ProtoReflect.Descriptor instead.
func (*GetPolicyRequest) Descriptor() ([]byte, []int) {
	return file_marchproxy_media_proto_rawDescGZIP(), []int{6}
}

func (x *GetPolicyRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type GetPolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policy        *MediaPolicy           `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	LastUpdated   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,3,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPolicyResponse) Reset() {
	*x = GetPolicyResponse{}
	mi := &file_marchproxy_media_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPolicyResponse) ProtoMessage() {}

func (x *GetPolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marchproxy_media_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPolicyResponse.ProtoReflect.Descriptor instead.
func (*GetPolicyResponse) Descriptor() ([]byte, []int) {
	return file_marchproxy_media_proto_rawDescGZIP(), []int{7}
}

func (x *GetPolicyResponse) GetPolicy() *MediaPolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *GetPolicyResponse) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

func (x *GetPolicyResponse) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

type ListStreamsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InstanceId     string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Query          *Query                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`                                                                              // Optional filtering and pagination
	ProtocolFilter MediaStreamProtocol    `protobuf:"varint,3,opt,name=protocol_filter,json=protocolFilter,proto3,enum=marchproxy.MediaStreamProtocol" json:"protocol_filter,omitempty"` // Optional: filter by protocol
	StatusFilter   string                 `protobuf:"bytes,4,opt,name=status_filter,json=statusFilter,proto3" json:"status_filter,omitempty"`                                            // Optional: filter by status
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListStreamsRequest) Reset() {
	*x = ListStreamsRequest{}
	mi := &file_marchproxy_media_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStreamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStreamsRequest) ProtoMessage() {}

func (x *ListStreamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marchproxy_media_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStreamsRequest.ProtoReflect.Descriptor instead.
func (*ListStreamsRequest) Descriptor() ([]byte, []int) {
	return file_marchproxy_media_proto_rawDescGZIP(), []int{8}
}

func (x *ListStreamsRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *ListStreamsRequest) GetQuery() *Query {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *ListStreamsRequest) GetProtocolFilter() MediaStreamProtocol {
	if x != nil {
		return x.ProtocolFilter
	}
	return MediaStreamProtocol_MEDIA_STREAM_PROTOCOL_UNSPECIFIED
}

func (x *ListStreamsRequest) GetStatusFilter() string {
	if x != nil {
		return x.StatusFilter
	}
	return ""
}

type ListStreamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Streams       []*MediaStream         `protobuf:"bytes,1,rep,name=streams,proto3" json:"streams,omitempty"`
	TotalStreams  int32                  `protobuf:"varint,2,opt,name=total_streams,json=totalStreams,proto3" json:"total_streams,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStreamsResponse) Reset() {
	*x = ListStreamsResponse{}
	mi := &file_marchproxy_media_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStreamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStreamsResponse) ProtoMessage() {}

func (x *ListStreamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marchproxy_media_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStreamsResponse.ProtoReflect.Descriptor instead.
func (*ListStreamsResponse) Descriptor() ([]byte, []int) {
	return file_marchproxy_media_proto_rawDescGZIP(), []int{9}
}

func (x *ListStreamsResponse) GetStreams() []*MediaStream {
	if x != nil {
		return x.Streams
	}
	return nil
}

func (x *ListStreamsResponse) GetTotalStreams() int32 {
	if x != nil {
		return x.TotalStreams
	}
	return 0
}

func (x *ListStreamsResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type GetStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	StreamKey     string                 `protobuf:"bytes,2,opt,name=stream_key,json=streamKey,proto3" json:"stream_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStreamRequest) Reset() {
	*x = GetStreamRequest{}
	mi := &file_marchproxy_media_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamRequest) ProtoMessage() {}

func (x *GetStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marchproxy_media_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamRequest.ProtoReflect.Descriptor instead.
func (*GetStreamRequest) Descriptor() ([]byte, []int) {
	return file_marchproxy_media_proto_rawDescGZIP(), []int{10}
}

func (x *GetStreamRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *GetStreamRequest) GetStreamKey() string {
	if x != nil {
		return x.StreamKey
	}
	return ""
}

type GetStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stream        *MediaStream           `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStreamResponse) Reset() {
	*x = GetStreamResponse{}
	mi := &file_marchproxy_media_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamResponse) ProtoMessage() {}

func (x *GetStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marchproxy_media_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamResponse.ProtoReflect.Descriptor instead.
func (*GetStreamResponse) Descriptor() ([]byte, []int) {
	return file_marchproxy_media_proto_rawDescGZIP(), []int{11}
}

func (x *GetStreamResponse) GetStream() *MediaStream {
	if x != nil {
		return x.Stream
	}
	return nil
}

func (x *GetStreamResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type StopStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	StreamKey     string                 `protobuf:"bytes,2,opt,name=stream_key,json=streamKey,proto3" json:"stream_key,omitempty"`
	Graceful      bool                   `protobuf:"varint,3,opt,name=graceful,proto3" json:"graceful,omitempty"` // Graceful stop (flush buffers)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopStreamRequest) Reset() {
	*x = StopStreamRequest{}
	mi := &file_marchproxy_media_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopStreamRequest) ProtoMessage() {}

func (x *StopStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marchproxy_media_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopStreamRequest.ProtoReflect.Descriptor instead.
func (*StopStreamRequest) Descriptor() ([]byte, []int) {
	return file_marchproxy_media_proto_rawDescGZIP(), []int{12}
}

func (x *StopStreamRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *StopStreamRequest) GetStreamKey() string {
	if x != nil {
		return x.StreamKey
	}
	return ""
}

func (x *StopStreamRequest) GetGraceful() bool {
	if x != nil {
		return x.Graceful
	}
	return false
}

type StopStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error         *Error                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopStreamResponse) Reset() {
	*x = StopStreamResponse{}
	mi := &file_marchproxy_media_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopStreamResponse) ProtoMessage() {}

func (x *StopStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marchproxy_media_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopStreamResponse.ProtoReflect.Descriptor instead.
func (*StopStreamResponse) Descriptor() ([]byte, []int) {
	return file_marchproxy_media_proto_rawDescGZIP(), []int{13}
}

func (x *StopStreamResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StopStreamResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StopStreamResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetStreamStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	StreamKey     string                 `protobuf:"bytes,2,opt,name=stream_key,json=streamKey,proto3" json:"stream_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStreamStatsRequest) Reset() {
	*x = GetStreamStatsRequest{}
	mi := &file_marchproxy_media_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreamStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamStatsRequest) ProtoMessage() {}

func (x *GetStreamStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marchproxy_media_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStreamStatsRequest) Descriptor() ([]byte, []int) {
	return file_marchproxy_media_proto_rawDescGZIP(), []int{14}
}

func (x *GetStreamStatsRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *GetStreamStatsRequest) GetStreamKey() string {
	if x != nil {
		return x.StreamKey
	}
	return ""
}

type GetStreamStatsResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Stream              *MediaStream           `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	DurationSeconds     int64                  `protobuf:"varint,2,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	AvgBitrateKbps      float64                `protobuf:"fixed64,3,opt,name=avg_bitrate_kbps,json=avgBitrateKbps,proto3" json:"avg_bitrate_kbps,omitempty"`
	DroppedFrames       int64                  `protobuf:"varint,4,opt,name=dropped_frames,json=droppedFrames,proto3" json:"dropped_frames,omitempty"`
	BufferHealthPercent float64                `protobuf:"fixed64,5,opt,name=buffer_health_percent,json=bufferHealthPercent,proto3" json:"buffer_health_percent,omitempty"`
	EncoderStats        map[string]string      `protobuf:"bytes,6,rep,name=encoder_stats,json=encoderStats,proto3" json:"encoder_stats,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetStreamStatsResponse) Reset() {
	*x = GetStreamStatsResponse{}
	mi := &file_marchproxy_media_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreamStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamStatsResponse) ProtoMessage() {}

func (x *GetStreamStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marchproxy_media_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStreamStatsResponse) Descriptor() ([]byte, []int) {
	return file_marchproxy_media_proto_rawDescGZIP(), []int{15}
}

func (x *GetStreamStatsResponse) GetStream() *MediaStream {
	if x != nil {
		return x.Stream
	}
	return nil
}

func (x *GetStreamStatsResponse) GetDurationSeconds() int64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *GetStreamStatsResponse) GetAvgBitrateKbps() float64 {
	if x != nil {
		return x.AvgBitrateKbps
	}
	return 0
}

func (x *GetStreamStatsResponse) GetDroppedFrames() int64 {
	if x != nil {
		return x.DroppedFrames
	}
	return 0
}

func (x *GetStreamStatsResponse) GetBufferHealthPercent() float64 {
	if x != nil {
		return x.BufferHealthPercent
	}
	return 0
}

func (x *GetStreamStatsResponse) GetEncoderStats() map[string]string {
	if x != nil {
		return x.EncoderStats
	}
	return nil
}

type GetBitrateProfilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBitrateProfilesRequest) Reset() {
	*x = GetBitrateProfilesRequest{}
	mi := &file_marchproxy_media_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBitrateProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBitrateProfilesRequest) ProtoMessage() {}

func (x *GetBitrateProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marchproxy_media_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBitrateProfilesRequest.ProtoReflect.Descriptor instead.
func (*GetBitrateProfilesRequest) Descriptor() ([]byte, []int) {
	return file_marchproxy_media_proto_rawDescGZIP(), []int{16}
}

func (x *GetBitrateProfilesRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type GetBitrateProfilesResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Profiles           []*BitrateProfile      `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	EnabledResolutions []int32                `protobuf:"varint,2,rep,packed,name=enabled_resolutions,json=enabledResolutions,proto3" json:"enabled_resolutions,omitempty"` // Which resolutions are enabled
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetBitrateProfilesResponse) Reset() {
	*x = GetBitrateProfilesResponse{}
	mi := &file_marchproxy_media_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBitrateProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBitrateProfilesResponse) ProtoMessage() {}

func (x *GetBitrateProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marchproxy_media_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBitrateProfilesResponse.ProtoReflect.Descriptor instead.
func (*GetBitrateProfilesResponse) Descriptor() ([]byte, []int) {
	return file_marchproxy_media_proto_rawDescGZIP(), []int{17}
}

func (x *GetBitrateProfilesResponse) GetProfiles() []*BitrateProfile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

func (x *GetBitrateProfilesResponse) GetEnabledResolutions() []int32 {
	if x != nil {
		return x.EnabledResolutions
	}
	return nil
}

type SetBitrateProfilesRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	InstanceId         string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Profiles           []*BitrateProfile      `protobuf:"bytes,2,rep,name=profiles,proto3" json:"profiles,omitempty"`
	EnabledResolutions []int32                `protobuf:"varint,3,rep,packed,name=enabled_resolutions,json=enabledResolutions,proto3" json:"enabled_resolutions,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SetBitrateProfilesRequest) Reset() {
	*x = SetBitrateProfilesRequest{}
	mi := &file_marchproxy_media_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBitrateProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBitrateProfilesRequest) ProtoMessage() {}

func (x *SetBitrateProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marchproxy_media_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBitrateProfilesRequest.ProtoReflect.Descriptor instead.
func (*SetBitrateProfilesRequest) Descriptor() ([]byte, []int) {
	return file_marchproxy_media_proto_rawDescGZIP(), []int{18}
}

func (x *SetBitrateProfilesRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *SetBitrateProfilesRequest) GetProfiles() []*BitrateProfile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

func (x *SetBitrateProfilesRequest) GetEnabledResolutions() []int32 {
	if x != nil {
		return x.EnabledResolutions
	}
	return nil
}

type SetBitrateProfilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error         *Error                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBitrateProfilesResponse) Reset() {
	*x = SetBitrateProfilesResponse{}
	mi := &file_marchproxy_media_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBitrateProfilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBitrateProfilesResponse) ProtoMessage() {}

func (x *SetBitrateProfilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marchproxy_media_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBitrateProfilesResponse.ProtoReflect.Descriptor instead.
func (*SetBitrateProfilesResponse) Descriptor() ([]byte, []int) {
	return file_marchproxy_media_proto_rawDescGZIP(), []int{19}
}

func (x *SetBitrateProfilesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetBitrateProfilesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SetBitrateProfilesResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type AddRestreamDestinationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	StreamKey     string                 `protobuf:"bytes,2,opt,name=stream_key,json=streamKey,proto3" json:"stream_key,omitempty"` // Source stream key
	Destination   *RestreamDestination   `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRestreamDestinationRequest) Reset() {
	*x = AddRestreamDestinationRequest{}
	mi := &file_marchproxy_media_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRestreamDestinationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRestreamDestinationRequest) ProtoMessage() {}

func (x *AddRestreamDestinationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marchproxy_media_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRestreamDestinationRequest.ProtoReflect.Descriptor instead.
func (*AddRestreamDestinationRequest) Descriptor() ([]byte, []int) {
	return file_marchproxy_media_proto_rawDescGZIP(), []int{20}
}

func (x *AddRestreamDestinationRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *AddRestreamDestinationRequest) GetStreamKey() string {
	if x != nil {
		return x.StreamKey
	}
	return ""
}

func (x *AddRestreamDestinationRequest) GetDestination() *RestreamDestination {
	if x != nil {
		return x.Destination
	}
	return nil
}

type AddRestreamDestinationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DestinationId string                 `protobuf:"bytes,3,opt,name=destination_id,json=destinationId,proto3" json:"destination_id,omitempty"`
	Error         *Error                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRestreamDestinationResponse) Reset() {
	*x = AddRestreamDestinationResponse{}
	mi := &file_marchproxy_media_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRestreamDestinationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRestreamDestinationResponse) ProtoMessage() {}

func (x *AddRestreamDestinationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marchproxy_media_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRestreamDestinationResponse.ProtoReflect.Descriptor instead.
func (*AddRestreamDestinationResponse) Descriptor() ([]byte, []int) {
	return file_marchproxy_media_proto_rawDescGZIP(), []int{21}
}

func (x *AddRestreamDestinationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddRestreamDestinationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AddRestreamDestinationResponse) GetDestinationId() string {
	if x != nil {
		return x.DestinationId
	}
	return ""
}

func (x *AddRestreamDestinationResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type RemoveRestreamDestinationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	StreamKey     string                 `protobuf:"bytes,2,opt,name=stream_key,json=streamKey,proto3" json:"stream_key,omitempty"`
	DestinationId string                 `protobuf:"bytes,3,opt,name=destination_id,json=destinationId,proto3" json:"destination_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRestreamDestinationRequest) Reset() {
	*x = RemoveRestreamDestinationRequest{}
	mi := &file_marchproxy_media_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRestreamDestinationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRestreamDestinationRequest) ProtoMessage() {}

func (x *RemoveRestreamDestinationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marchproxy_media_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRestreamDestinationRequest.ProtoReflect.Descriptor instead.
func (*RemoveRestreamDestinationRequest) Descriptor() ([]byte, []int) {
	return file_marchproxy_media_proto_rawDescGZIP(), []int{22}
}

func (x *RemoveRestreamDestinationRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *RemoveRestreamDestinationRequest) GetStreamKey() string {
	if x != nil {
		return x.StreamKey
	}
	return ""
}

func (x *RemoveRestreamDestinationRequest) GetDestinationId() string {
	if x != nil {
		return x.DestinationId
	}
	return ""
}

type RemoveRestreamDestinationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error         *Error                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRestreamDestinationResponse) Reset() {
	*x = RemoveRestreamDestinationResponse{}
	mi := &file_marchproxy_media_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRestreamDestinationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRestreamDestinationResponse) ProtoMessage() {}

func (x *RemoveRestreamDestinationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marchproxy_media_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRestreamDestinationResponse.ProtoReflect.Descriptor instead.
func (*RemoveRestreamDestinationResponse) Descriptor() ([]byte, []int) {
	return file_marchproxy_media_proto_rawDescGZIP(), []int{23}
}

func (x *RemoveRestreamDestinationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoveRestreamDestinationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RemoveRestreamDestinationResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type ListRestreamDestinationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	StreamKey     string                 `protobuf:"bytes,2,opt,name=stream_key,json=streamKey,proto3" json:"stream_key,omitempty"` // Optional: filter by stream
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRestreamDestinationsRequest) Reset() {
	*x = ListRestreamDestinationsRequest{}
	mi := &file_marchproxy_media_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRestreamDestinationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRestreamDestinationsRequest) ProtoMessage() {}

func (x *ListRestreamDestinationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marchproxy_media_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRestreamDestinationsRequest.ProtoReflect.Descriptor instead.
func (*ListRestreamDestinationsRequest) Descriptor() ([]byte, []int) {
	return file_marchproxy_media_proto_rawDescGZIP(), []int{24}
}

func (x *ListRestreamDestinationsRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *ListRestreamDestinationsRequest) GetStreamKey() string {
	if x != nil {
		return x.StreamKey
	}
	return ""
}

type ListRestreamDestinationsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Destinations      []*RestreamDestination `protobuf:"bytes,1,rep,name=destinations,proto3" json:"destinations,omitempty"`
	TotalDestinations int32                  `protobuf:"varint,2,opt,name=total_destinations,json=totalDestinations,proto3" json:"total_destinations,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListRestreamDestinationsResponse) Reset() {
	*x = ListRestreamDestinationsResponse{}
	mi := &file_marchproxy_media_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRestreamDestinationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRestreamDestinationsResponse) ProtoMessage() {}

func (x *ListRestreamDestinationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marchproxy_media_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRestreamDestinationsResponse.ProtoReflect.Descriptor instead.
func (*ListRestreamDestinationsResponse) Descriptor() ([]byte, []int) {
	return file_marchproxy_media_proto_rawDescGZIP(), []int{25}
}

func (x *ListRestreamDestinationsResponse) GetDestinations() []*RestreamDestination {
	if x != nil {
		return x.Destinations
	}
	return nil
}

func (x *ListRestreamDestinationsResponse) GetTotalDestinations() int32 {
	if x != nil {
		return x.TotalDestinations
	}
	return 0
}

type StartRestreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	StreamKey     string                 `protobuf:"bytes,2,opt,name=stream_key,json=streamKey,proto3" json:"stream_key,omitempty"`
	DestinationId string                 `protobuf:"bytes,3,opt,name=destination_id,json=destinationId,proto3" json:"destination_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRestreamRequest) Reset() {
	*x = StartRestreamRequest{}
	mi := &file_marchproxy_media_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRestreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRestreamRequest) ProtoMessage() {}

func (x *StartRestreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marchproxy_media_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRestreamRequest.ProtoReflect.Descriptor instead.
func (*StartRestreamRequest) Descriptor() ([]byte, []int) {
	return file_marchproxy_media_proto_rawDescGZIP(), []int{26}
}

func (x *StartRestreamRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *StartRestreamRequest) GetStreamKey() string {
	if x != nil {
		return x.StreamKey
	}
	return ""
}

func (x *StartRestreamRequest) GetDestinationId() string {
	if x != nil {
		return x.DestinationId
	}
	return ""
}

type StartRestreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error         *Error                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRestreamResponse) Reset() {
	*x = StartRestreamResponse{}
	mi := &file_marchproxy_media_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRestreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRestreamResponse) ProtoMessage() {}

func (x *StartRestreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marchproxy_media_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRestreamResponse.ProtoReflect.Descriptor instead.
func (*StartRestreamResponse) Descriptor() ([]byte, []int) {
	return file_marchproxy_media_proto_rawDescGZIP(), []int{27}
}

func (x *StartRestreamResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartRestreamResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StartRestreamResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type StopRestreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	StreamKey     string                 `protobuf:"bytes,2,opt,name=stream_key,json=streamKey,proto3" json:"stream_key,omitempty"`
	DestinationId string                 `protobuf:"bytes,3,opt,name=destination_id,json=destinationId,proto3" json:"destination_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRestreamRequest) Reset() {
	*x = StopRestreamRequest{}
	mi := &file_marchproxy_media_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRestreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRestreamRequest) ProtoMessage() {}

func (x *StopRestreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marchproxy_media_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRestreamRequest.ProtoReflect.Descriptor instead.
func (*StopRestreamRequest) Descriptor() ([]byte, []int) {
	return file_marchproxy_media_proto_rawDescGZIP(), []int{28}
}

func (x *StopRestreamRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *StopRestreamRequest) GetStreamKey() string {
	if x != nil {
		return x.StreamKey
	}
	return ""
}

func (x *StopRestreamRequest) GetDestinationId() string {
	if x != nil {
		return x.DestinationId
	}
	return ""
}

type StopRestreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Error         *Error                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRestreamResponse) Reset() {
	*x = StopRestreamResponse{}
	mi := &file_marchproxy_media_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRestreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRestreamResponse) ProtoMessage() {}

func (x *StopRestreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marchproxy_media_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRestreamResponse.ProtoReflect.Descriptor instead.
func (*StopRestreamResponse) Descriptor() ([]byte, []int) {
	return file_marchproxy_media_proto_rawDescGZIP(), []int{29}
}

func (x *StopRestreamResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StopRestreamResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StopRestreamResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetMediaStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	ResetCounters bool                   `protobuf:"varint,2,opt,name=reset_counters,json=resetCounters,proto3" json:"reset_counters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaStatsRequest) Reset() {
	*x = GetMediaStatsRequest{}
	mi := &file_marchproxy_media_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaStatsRequest) ProtoMessage() {}

func (x *GetMediaStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marchproxy_media_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaStatsRequest.ProtoReflect.Descriptor instead.
func (*GetMediaStatsRequest) Descriptor() ([]byte, []int) {
	return file_marchproxy_media_proto_rawDescGZIP(), []int{30}
}

func (x *GetMediaStatsRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *GetMediaStatsRequest) GetResetCounters() bool {
	if x != nil {
		return x.ResetCounters
	}
	return false
}

type GetMediaStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *MediaModuleStats      `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	Capabilities  *MediaCapabilities     `protobuf:"bytes,2,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaStatsResponse) Reset() {
	*x = GetMediaStatsResponse{}
	mi := &file_marchproxy_media_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaStatsResponse) ProtoMessage() {}

func (x *GetMediaStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marchproxy_media_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaStatsResponse.ProtoReflect.Descriptor instead.
func (*GetMediaStatsResponse) Descriptor() ([]byte, []int) {
	return file_marchproxy_media_proto_rawDescGZIP(), []int{31}
}

func (x *GetMediaStatsResponse) GetStats() *MediaModuleStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *GetMediaStatsResponse) GetCapabilities() *MediaCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type StreamMediaStatsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InstanceId      string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	IntervalSeconds int32                  `protobuf:"varint,2,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"` // Streaming interval (default 5s)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StreamMediaStatsRequest) Reset() {
	*x = StreamMediaStatsRequest{}
	mi := &file_marchproxy_media_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMediaStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMediaStatsRequest) ProtoMessage() {}

func (x *StreamMediaStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marchproxy_media_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMediaStatsRequest.ProtoReflect.Descriptor instead.
func (*StreamMediaStatsRequest) Descriptor() ([]byte, []int) {
	return file_marchproxy_media_proto_rawDescGZIP(), []int{32}
}

func (x *StreamMediaStatsRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *StreamMediaStatsRequest) GetIntervalSeconds() int32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

type StreamMediaStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *MediaModuleStats      `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	ActiveStreams []*MediaStream         `protobuf:"bytes,2,rep,name=active_streams,json=activeStreams,proto3" json:"active_streams,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMediaStatsResponse) Reset() {
	*x = StreamMediaStatsResponse{}
	mi := &file_marchproxy_media_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMediaStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMediaStatsResponse) ProtoMessage() {}

func (x *StreamMediaStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marchproxy_media_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMediaStatsResponse.ProtoReflect.Descriptor instead.
func (*StreamMediaStatsResponse) Descriptor() ([]byte, []int) {
	return file_marchproxy_media_proto_rawDescGZIP(), []int{33}
}

func (x *StreamMediaStatsResponse) GetStats() *MediaModuleStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *StreamMediaStatsResponse) GetActiveStreams() []*MediaStream {
	if x != nil {
		return x.ActiveStreams
	}
	return nil
}

func (x *StreamMediaStatsResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_marchproxy_media_proto protoreflect.FileDescriptor

const file_marchproxy_media_proto_rawDesc = "" +
	"\n" +
	"\x16marchproxy/media.proto\x12\n" +
	"marchproxy\x1a\x16marchproxy/types.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"9\n" +
	"\x16GetCapabilitiesRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\"\x99\x01\n" +
	"\x17GetCapabilitiesResponse\x12A\n" +
	"\fcapabilities\x18\x01 \x01(\v2\x1d.marchproxy.MediaCapabilitiesR\fcapabilities\x12;\n" +
	"\vdetected_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"detectedAt\"<\n" +
	"\x19GetEffectiveLimitsRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\"\x81\x03\n" +
	"\x1aGetEffectiveLimitsResponse\x128\n" +
	"\x18effective_max_resolution\x18\x01 \x01(\x05R\x16effectiveMaxResolution\x12;\n" +
	"\x1aeffective_max_bitrate_kbps\x18\x02 \x01(\x05R\x17effectiveMaxBitrateKbps\x126\n" +
	"\x17hardware_max_resolution\x18\x03 \x01(\x05R\x15hardwareMaxResolution\x125\n" +
	"\x14admin_max_resolution\x18\x04 \x01(\x05H\x00R\x12adminMaxResolution\x88\x01\x01\x12!\n" +
	"\flimit_reason\x18\x05 \x01(\tR\vlimitReason\x12A\n" +
	"\fcapabilities\x18\x06 \x01(\v2\x1d.marchproxy.MediaCapabilitiesR\fcapabilitiesB\x17\n" +
	"\x15_admin_max_resolution\"z\n" +
	"\x13UpdatePolicyRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12B\n" +
	"\rpolicy_update\x18\x02 \x01(\v2\x1d.marchproxy.MediaPolicyUpdateR\fpolicyUpdate\"\xb3\x01\n" +
	"\x14UpdatePolicyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12>\n" +
	"\x0eapplied_policy\x18\x03 \x01(\v2\x17.marchproxy.MediaPolicyR\rappliedPolicy\x12'\n" +
	"\x05error\x18\x04 \x01(\v2\x11.marchproxy.ErrorR\x05error\"3\n" +
	"\x10GetPolicyRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\"\xa2\x01\n" +
	"\x11GetPolicyResponse\x12/\n" +
	"\x06policy\x18\x01 \x01(\v2\x17.marchproxy.MediaPolicyR\x06policy\x12=\n" +
	"\flast_updated\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x03 \x01(\tR\tupdatedBy\"\xcd\x01\n" +
	"\x12ListStreamsRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12'\n" +
	"\x05query\x18\x02 \x01(\v2\x11.marchproxy.QueryR\x05query\x12H\n" +
	"\x0fprotocol_filter\x18\x03 \x01(\x0e2\x1f.marchproxy.MediaStreamProtocolR\x0eprotocolFilter\x12#\n" +
	"\rstatus_filter\x18\x04 \x01(\tR\fstatusFilter\"\xa5\x01\n" +
	"\x13ListStreamsResponse\x121\n" +
	"\astreams\x18\x01 \x03(\v2\x17.marchproxy.MediaStreamR\astreams\x12#\n" +
	"\rtotal_streams\x18\x02 \x01(\x05R\ftotalStreams\x126\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2\x16.marchproxy.PaginationR\n" +
	"pagination\"R\n" +
	"\x10GetStreamRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x1d\n" +
	"\n" +
	"stream_key\x18\x02 \x01(\tR\tstreamKey\"Z\n" +
	"\x11GetStreamResponse\x12/\n" +
	"\x06stream\x18\x01 \x01(\v2\x17.marchproxy.MediaStreamR\x06stream\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"o\n" +
	"\x11StopStreamRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x1d\n" +
	"\n" +
	"stream_key\x18\x02 \x01(\tR\tstreamKey\x12\x1a\n" +
	"\bgraceful\x18\x03 \x01(\bR\bgraceful\"q\n" +
	"\x12StopStreamResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x05error\x18\x03 \x01(\v2\x11.marchproxy.ErrorR\x05error\"W\n" +
	"\x15GetStreamStatsRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x1d\n" +
	"\n" +
	"stream_key\x18\x02 \x01(\tR\tstreamKey\"\x95\x03\n" +
	"\x16GetStreamStatsResponse\x12/\n" +
	"\x06stream\x18\x01 \x01(\v2\x17.marchproxy.MediaStreamR\x06stream\x12)\n" +
	"\x10duration_seconds\x18\x02 \x01(\x03R\x0fdurationSeconds\x12(\n" +
	"\x10avg_bitrate_kbps\x18\x03 \x01(\x01R\x0eavgBitrateKbps\x12%\n" +
	"\x0edropped_frames\x18\x04 \x01(\x03R\rdroppedFrames\x122\n" +
	"\x15buffer_health_percent\x18\x05 \x01(\x01R\x13bufferHealthPercent\x12Y\n" +
	"\rencoder_stats\x18\x06 \x03(\v24.marchproxy.GetStreamStatsResponse.EncoderStatsEntryR\fencoderStats\x1a?\n" +
	"\x11EncoderStatsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"<\n" +
	"\x19GetBitrateProfilesRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\"\x85\x01\n" +
	"\x1aGetBitrateProfilesResponse\x126\n" +
	"\bprofiles\x18\x01 \x03(\v2\x1a.marchproxy.BitrateProfileR\bprofiles\x12/\n" +
	"\x13enabled_resolutions\x18\x02 \x03(\x05R\x12enabledResolutions\"\xa5\x01\n" +
	"\x19SetBitrateProfilesRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x126\n" +
	"\bprofiles\x18\x02 \x03(\v2\x1a.marchproxy.BitrateProfileR\bprofiles\x12/\n" +
	"\x13enabled_resolutions\x18\x03 \x03(\x05R\x12enabledResolutions\"y\n" +
	"\x1aSetBitrateProfilesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x05error\x18\x03 \x01(\v2\x11.marchproxy.ErrorR\x05error\"\xa2\x01\n" +
	"\x1dAddRestreamDestinationRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x1d\n" +
	"\n" +
	"stream_key\x18\x02 \x01(\tR\tstreamKey\x12A\n" +
	"\vdestination\x18\x03 \x01(\v2\x1f.marchproxy.RestreamDestinationR\vdestination\"\xa4\x01\n" +
	"\x1eAddRestreamDestinationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0edestination_id\x18\x03 \x01(\tR\rdestinationId\x12'\n" +
	"\x05error\x18\x04 \x01(\v2\x11.marchproxy.ErrorR\x05error\"\x89\x01\n" +
	" RemoveRestreamDestinationRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x1d\n" +
	"\n" +
	"stream_key\x18\x02 \x01(\tR\tstreamKey\x12%\n" +
	"\x0edestination_id\x18\x03 \x01(\tR\rdestinationId\"\x80\x01\n" +
	"!RemoveRestreamDestinationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x05error\x18\x03 \x01(\v2\x11.marchproxy.ErrorR\x05error\"a\n" +
	"\x1fListRestreamDestinationsRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x1d\n" +
	"\n" +
	"stream_key\x18\x02 \x01(\tR\tstreamKey\"\x96\x01\n" +
	" ListRestreamDestinationsResponse\x12C\n" +
	"\fdestinations\x18\x01 \x03(\v2\x1f.marchproxy.RestreamDestinationR\fdestinations\x12-\n" +
	"\x12total_destinations\x18\x02 \x01(\x05R\x11totalDestinations\"}\n" +
	"\x14StartRestreamRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x1d\n" +
	"\n" +
	"stream_key\x18\x02 \x01(\tR\tstreamKey\x12%\n" +
	"\x0edestination_id\x18\x03 \x01(\tR\rdestinationId\"t\n" +
	"\x15StartRestreamResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x05error\x18\x03 \x01(\v2\x11.marchproxy.ErrorR\x05error\"|\n" +
	"\x13StopRestreamRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x1d\n" +
	"\n" +
	"stream_key\x18\x02 \x01(\tR\tstreamKey\x12%\n" +
	"\x0edestination_id\x18\x03 \x01(\tR\rdestinationId\"s\n" +
	"\x14StopRestreamResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x05error\x18\x03 \x01(\v2\x11.marchproxy.ErrorR\x05error\"^\n" +
	"\x14GetMediaStatsRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12%\n" +
	"\x0ereset_counters\x18\x02 \x01(\bR\rresetCounters\"\x8e\x01\n" +
	"\x15GetMediaStatsResponse\x122\n" +
	"\x05stats\x18\x01 \x01(\v2\x1c.marchproxy.MediaModuleStatsR\x05stats\x12A\n" +
	"\fcapabilities\x18\x02 \x01(\v2\x1d.marchproxy.MediaCapabilitiesR\fcapabilities\"e\n" +
	"\x17StreamMediaStatsRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12)\n" +
	"\x10interval_seconds\x18\x02 \x01(\x05R\x0fintervalSeconds\"\xc8\x01\n" +
	"\x18StreamMediaStatsResponse\x122\n" +
	"\x05stats\x18\x01 \x01(\v2\x1c.marchproxy.MediaModuleStatsR\x05stats\x12>\n" +
	"\x0eactive_streams\x18\x02 \x03(\v2\x17.marchproxy.MediaStreamR\ractiveStreams\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp2\xb8\f\n" +
	"\fMediaService\x12Z\n" +
	"\x0fGetCapabilities\x12\".marchproxy.GetCapabilitiesRequest\x1a#.marchproxy.GetCapabilitiesResponse\x12c\n" +
	"\x12GetEffectiveLimits\x12%.marchproxy.GetEffectiveLimitsRequest\x1a&.marchproxy.GetEffectiveLimitsResponse\x12Q\n" +
	"\fUpdatePolicy\x12\x1f.marchproxy.UpdatePolicyRequest\x1a .marchproxy.UpdatePolicyResponse\x12H\n" +
	"\tGetPolicy\x12\x1c.marchproxy.GetPolicyRequest\x1a\x1d.marchproxy.GetPolicyResponse\x12N\n" +
	"\vListStreams\x12\x1e.marchproxy.ListStreamsRequest\x1a\x1f.marchproxy.ListStreamsResponse\x12H\n" +
	"\tGetStream\x12\x1c.marchproxy.GetStreamRequest\x1a\x1d.marchproxy.GetStreamResponse\x12K\n" +
	"\n" +
	"StopStream\x12\x1d.marchproxy.StopStreamRequest\x1a\x1e.marchproxy.StopStreamResponse\x12W\n" +
	"\x0eGetStreamStats\x12!.marchproxy.GetStreamStatsRequest\x1a\".marchproxy.GetStreamStatsResponse\x12c\n" +
	"\x12GetBitrateProfiles\x12%.marchproxy.GetBitrateProfilesRequest\x1a&.marchproxy.GetBitrateProfilesResponse\x12c\n" +
	"\x12SetBitrateProfiles\x12%.marchproxy.SetBitrateProfilesRequest\x1a&.marchproxy.SetBitrateProfilesResponse\x12o\n" +
	"\x16AddRestreamDestination\x12).marchproxy.AddRestreamDestinationRequest\x1a*.marchproxy.AddRestreamDestinationResponse\x12x\n" +
	"\x19RemoveRestreamDestination\x12,.marchproxy.RemoveRestreamDestinationRequest\x1a-.marchproxy.RemoveRestreamDestinationResponse\x12u\n" +
	"\x18ListRestreamDestinations\x12+.marchproxy.ListRestreamDestinationsRequest\x1a,.marchproxy.ListRestreamDestinationsResponse\x12T\n" +
	"\rStartRestream\x12 .marchproxy.StartRestreamRequest\x1a!.marchproxy.StartRestreamResponse\x12Q\n" +
	"\fStopRestream\x12\x1f.marchproxy.StopRestreamRequest\x1a .marchproxy.StopRestreamResponse\x12T\n" +
	"\rGetMediaStats\x12 .marchproxy.GetMediaStatsRequest\x1a!.marchproxy.GetMediaStatsResponse\x12_\n" +
	"\x10StreamMediaStats\x12#.marchproxy.StreamMediaStatsRequest\x1a$.marchproxy.StreamMediaStatsResponse0\x01B?Z=github.com/penguintech/marchproxy/proto/marchproxy;marchproxyb\x06proto3"

var (
	file_marchproxy_media_proto_rawDescOnce sync.Once
	file_marchproxy_media_proto_rawDescData []byte
)

func file_marchproxy_media_proto_rawDescGZIP() []byte {
	file_marchproxy_media_proto_rawDescOnce.Do(func() {
		file_marchproxy_media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_marchproxy_media_proto_rawDesc), len(file_marchproxy_media_proto_rawDesc)))
	})
	return file_marchproxy_media_proto_rawDescData
}

var file_marchproxy_media_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_marchproxy_media_proto_goTypes = []any{
	(*GetCapabilitiesRequest)(nil),            // 0: marchproxy.GetCapabilitiesRequest
	(*GetCapabilitiesResponse)(nil),           // 1: marchproxy.GetCapabilitiesResponse
	(*GetEffectiveLimitsRequest)(nil),         // 2: marchproxy.GetEffectiveLimitsRequest
	(*GetEffectiveLimitsResponse)(nil),        // 3: marchproxy.GetEffectiveLimitsResponse
	(*UpdatePolicyRequest)(nil),               // 4: marchproxy.UpdatePolicyRequest
	(*UpdatePolicyResponse)(nil),              // 5: marchproxy.UpdatePolicyResponse
	(*GetPolicyRequest)(nil),                  // 6: marchproxy.GetPolicyRequest
	(*GetPolicyResponse)(nil),                 // 7: marchproxy.GetPolicyResponse
	(*ListStreamsRequest)(nil),                // 8: marchproxy.ListStreamsRequest
	(*ListStreamsResponse)(nil),               // 9: marchproxy.ListStreamsResponse
	(*GetStreamRequest)(nil),                  // 10: marchproxy.GetStreamRequest
	(*GetStreamResponse)(nil),                 // 11: marchproxy.GetStreamResponse
	(*StopStreamRequest)(nil),                 // 12: marchproxy.StopStreamRequest
	(*StopStreamResponse)(nil),                // 13: marchproxy.StopStreamResponse
	(*GetStreamStatsRequest)(nil),             // 14: marchproxy.GetStreamStatsRequest
	(*GetStreamStatsResponse)(nil),            // 15: marchproxy.GetStreamStatsResponse
	(*GetBitrateProfilesRequest)(nil),         // 16: marchproxy.GetBitrateProfilesRequest
	(*GetBitrateProfilesResponse)(nil),        // 17: marchproxy.GetBitrateProfilesResponse
	(*SetBitrateProfilesRequest)(nil),         // 18: marchproxy.SetBitrateProfilesRequest
	(*SetBitrateProfilesResponse)(nil),        // 19: marchproxy.SetBitrateProfilesResponse
	(*AddRestreamDestinationRequest)(nil),     // 20: marchproxy.AddRestreamDestinationRequest
	(*AddRestreamDestinationResponse)(nil),    // 21: marchproxy.AddRestreamDestinationResponse
	(*RemoveRestreamDestinationRequest)(nil),  // 22: marchproxy.RemoveRestreamDestinationRequest
	(*RemoveRestreamDestinationResponse)(nil), // 23: marchproxy.RemoveRestreamDestinationResponse
	(*ListRestreamDestinationsRequest)(nil),   // 24: marchproxy.ListRestreamDestinationsRequest
	(*ListRestreamDestinationsResponse)(nil),  // 25: marchproxy.ListRestreamDestinationsResponse
	(*StartRestreamRequest)(nil),              // 26: marchproxy.StartRestreamRequest
	(*StartRestreamResponse)(nil),             // 27: marchproxy.StartRestreamResponse
	(*StopRestreamRequest)(nil),               // 28: marchproxy.StopRestreamRequest
	(*StopRestreamResponse)(nil),              // 29: marchproxy.StopRestreamResponse
	(*GetMediaStatsRequest)(nil),              // 30: marchproxy.GetMediaStatsRequest
	(*GetMediaStatsResponse)(nil),             // 31: marchproxy.GetMediaStatsResponse
	(*StreamMediaStatsRequest)(nil),           // 32: marchproxy.StreamMediaStatsRequest
	(*StreamMediaStatsResponse)(nil),          // 33: marchproxy.StreamMediaStatsResponse
	nil,                                       // 34: marchproxy.GetStreamStatsResponse.EncoderStatsEntry
	(*MediaCapabilities)(nil),                 // 35: marchproxy.MediaCapabilities
	(*timestamppb.Timestamp)(nil),             // 36: google.protobuf.Timestamp
	(*MediaPolicyUpdate)(nil),                 // 37: marchproxy.MediaPolicyUpdate
	(*MediaPolicy)(nil),                       // 38: marchproxy.MediaPolicy
	(*Error)(nil),                             // 39: marchproxy.Error
	(*Query)(nil),                             // 40: marchproxy.Query
	(MediaStreamProtocol)(0),                  // 41: marchproxy.MediaStreamProtocol
	(*MediaStream)(nil),                       // 42: marchproxy.MediaStream
	(*Pagination)(nil),                        // 43: marchproxy.Pagination
	(*BitrateProfile)(nil),                    // 44: marchproxy.BitrateProfile
	(*RestreamDestination)(nil),               // 45: marchproxy.RestreamDestination
	(*MediaModuleStats)(nil),                  // 46: marchproxy.MediaModuleStats
}
var file_marchproxy_media_proto_depIdxs = []int32{
	35, // 0: marchproxy.GetCapabilitiesResponse.capabilities:type_name -> marchproxy.MediaCapabilities
	36, // 1: marchproxy.GetCapabilitiesResponse.detected_at:type_name -> google.protobuf.Timestamp
	35, // 2: marchproxy.GetEffectiveLimitsResponse.capabilities:type_name -> marchproxy.MediaCapabilities
	37, // 3: marchproxy.UpdatePolicyRequest.policy_update:type_name -> marchproxy.MediaPolicyUpdate
	38, // 4: marchproxy.UpdatePolicyResponse.applied_policy:type_name -> marchproxy.MediaPolicy
	39, // 5: marchproxy.UpdatePolicyResponse.error:type_name -> marchproxy.Error
	38, // 6: marchproxy.GetPolicyResponse.policy:type_name -> marchproxy.MediaPolicy
	36, // 7: marchproxy.GetPolicyResponse.last_updated:type_name -> google.protobuf.Timestamp
	40, // 8: marchproxy.ListStreamsRequest.query:type_name -> marchproxy.Query
	41, // 9: marchproxy.ListStreamsRequest.protocol_filter:type_name -> marchproxy.MediaStreamProtocol
	42, // 10: marchproxy.ListStreamsResponse.streams:type_name -> marchproxy.MediaStream
	43, // 11: marchproxy.ListStreamsResponse.pagination:type_name -> marchproxy.Pagination
	42, // 12: marchproxy.GetStreamResponse.stream:type_name -> marchproxy.MediaStream
	39, // 13: marchproxy.StopStreamResponse.error:type_name -> marchproxy.Error
	42, // 14: marchproxy.GetStreamStatsResponse.stream:type_name -> marchproxy.MediaStream
	34, // 15: marchproxy.GetStreamStatsResponse.encoder_stats:type_name -> marchproxy.GetStreamStatsResponse.EncoderStatsEntry
	44, // 16: marchproxy.GetBitrateProfilesResponse.profiles:type_name -> marchproxy.BitrateProfile
	44, // 17: marchproxy.SetBitrateProfilesRequest.profiles:type_name -> marchproxy.BitrateProfile
	39, // 18: marchproxy.SetBitrateProfilesResponse.error:type_name -> marchproxy.Error
	45, // 19: marchproxy.AddRestreamDestinationRequest.destination:type_name -> marchproxy.RestreamDestination
	39, // 20: marchproxy.AddRestreamDestinationResponse.error:type_name -> marchproxy.Error
	39, // 21: marchproxy.RemoveRestreamDestinationResponse.error:type_name -> marchproxy.Error
	45, // 22: marchproxy.ListRestreamDestinationsResponse.destinations:type_name -> marchproxy.RestreamDestination
	39, // 23: marchproxy.StartRestreamResponse.error:type_name -> marchproxy.Error
	39, // 24: marchproxy.StopRestreamResponse.error:type_name -> marchproxy.Error
	46, // 25: marchproxy.GetMediaStatsResponse.stats:type_name -> marchproxy.MediaModuleStats
	35, // 26: marchproxy.GetMediaStatsResponse.capabilities:type_name -> marchproxy.MediaCapabilities
	46, // 27: marchproxy.StreamMediaStatsResponse.stats:type_name -> marchproxy.MediaModuleStats
	42, // 28: marchproxy.StreamMediaStatsResponse.active_streams:type_name -> marchproxy.MediaStream
	36, // 29: marchproxy.StreamMediaStatsResponse.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 30: marchproxy.MediaService.GetCapabilities:input_type -> marchproxy.GetCapabilitiesRequest
	2,  // 31: marchproxy.MediaService.GetEffectiveLimits:input_type -> marchproxy.GetEffectiveLimitsRequest
	4,  // 32: marchproxy.MediaService.UpdatePolicy:input_type -> marchproxy.UpdatePolicyRequest
	6,  // 33: marchproxy.MediaService.GetPolicy:input_type -> marchproxy.GetPolicyRequest
	8,  // 34: marchproxy.MediaService.ListStreams:input_type -> marchproxy.ListStreamsRequest
	10, // 35: marchproxy.MediaService.GetStream:input_type -> marchproxy.GetStreamRequest
	12, // 36: marchproxy.MediaService.StopStream:input_type -> marchproxy.StopStreamRequest
	14, // 37: marchproxy.MediaService.GetStreamStats:input_type -> marchproxy.GetStreamStatsRequest
	16, // 38: marchproxy.MediaService.GetBitrateProfiles:input_type -> marchproxy.GetBitrateProfilesRequest
	18, // 39: marchproxy.MediaService.SetBitrateProfiles:input_type -> marchproxy.SetBitrateProfilesRequest
	20, // 40: marchproxy.MediaService.AddRestreamDestination:input_type -> marchproxy.AddRestreamDestinationRequest
	22, // 41: marchproxy.MediaService.RemoveRestreamDestination:input_type -> marchproxy.RemoveRestreamDestinationRequest
	24, // 42: marchproxy.MediaService.ListRestreamDestinations:input_type -> marchproxy.ListRestreamDestinationsRequest
	26, // 43: marchproxy.MediaService.StartRestream:input_type -> marchproxy.StartRestreamRequest
	28, // 44: marchproxy.MediaService.StopRestream:input_type -> marchproxy.StopRestreamRequest
	30, // 45: marchproxy.MediaService.GetMediaStats:input_type -> marchproxy.GetMediaStatsRequest
	32, // 46: marchproxy.MediaService.StreamMediaStats:input_type -> marchproxy.StreamMediaStatsRequest
	1,  // 47: marchproxy.MediaService.GetCapabilities:output_type -> marchproxy.GetCapabilitiesResponse
	3,  // 48: marchproxy.MediaService.GetEffectiveLimits:output_type -> marchproxy.GetEffectiveLimitsResponse
	5,  // 49: marchproxy.MediaService.UpdatePolicy:output_type -> marchproxy.UpdatePolicyResponse
	7,  // 50: marchproxy.MediaService.GetPolicy:output_type -> marchproxy.GetPolicyResponse
	9,  // 51: marchproxy.MediaService.ListStreams:output_type -> marchproxy.ListStreamsResponse
	11, // 52: marchproxy.MediaService.GetStream:output_type -> marchproxy.GetStreamResponse
	13, // 53: marchproxy.MediaService.StopStream:output_type -> marchproxy.StopStreamResponse
	15, // 54: marchproxy.MediaService.GetStreamStats:output_type -> marchproxy.GetStreamStatsResponse
	17, // 55: marchproxy.MediaService.GetBitrateProfiles:output_type -> marchproxy.GetBitrateProfilesResponse
	19, // 56: marchproxy.MediaService.SetBitrateProfiles:output_type -> marchproxy.SetBitrateProfilesResponse
	21, // 57: marchproxy.MediaService.AddRestreamDestination:output_type -> marchproxy.AddRestreamDestinationResponse
	23, // 58: marchproxy.MediaService.RemoveRestreamDestination:output_type -> marchproxy.RemoveRestreamDestinationResponse
	25, // 59: marchproxy.MediaService.ListRestreamDestinations:output_type -> marchproxy.ListRestreamDestinationsResponse
	27, // 60: marchproxy.MediaService.StartRestream:output_type -> marchproxy.StartRestreamResponse
	29, // 61: marchproxy.MediaService.StopRestream:output_type -> marchproxy.StopRestreamResponse
	31, // 62: marchproxy.MediaService.GetMediaStats:output_type -> marchproxy.GetMediaStatsResponse
	33, // 63: marchproxy.MediaService.StreamMediaStats:output_type -> marchproxy.StreamMediaStatsResponse
	47, // [47:64] is the sub-list for method output_type
	30, // [30:47] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_marchproxy_media_proto_init() }
func file_marchproxy_media_proto_init() {
	if File_marchproxy_media_proto != nil {
		return
	}
	file_marchproxy_types_proto_init()
	file_marchproxy_media_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_marchproxy_media_proto_rawDesc), len(file_marchproxy_media_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_marchproxy_media_proto_goTypes,
		DependencyIndexes: file_marchproxy_media_proto_depIdxs,
		MessageInfos:      file_marchproxy_media_proto_msgTypes,
	}.Build()
	File_marchproxy_media_proto = out.File
	file_marchproxy_media_proto_goTypes = nil
	file_marchproxy_media_proto_depIdxs = nil
}
