// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: marchproxy/module.proto

package marchproxy

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ModuleService_GetStatus_FullMethodName        = "/marchproxy.ModuleService/GetStatus"
	ModuleService_Reload_FullMethodName           = "/marchproxy.ModuleService/Reload"
	ModuleService_Shutdown_FullMethodName         = "/marchproxy.ModuleService/Shutdown"
	ModuleService_CanHandle_FullMethodName        = "/marchproxy.ModuleService/CanHandle"
	ModuleService_GetRoutes_FullMethodName        = "/marchproxy.ModuleService/GetRoutes"
	ModuleService_UpdateRoutes_FullMethodName     = "/marchproxy.ModuleService/UpdateRoutes"
	ModuleService_DeleteRoute_FullMethodName      = "/marchproxy.ModuleService/DeleteRoute"
	ModuleService_GetRateLimits_FullMethodName    = "/marchproxy.ModuleService/GetRateLimits"
	ModuleService_SetRateLimit_FullMethodName     = "/marchproxy.ModuleService/SetRateLimit"
	ModuleService_RemoveRateLimit_FullMethodName  = "/marchproxy.ModuleService/RemoveRateLimit"
	ModuleService_GetMetrics_FullMethodName       = "/marchproxy.ModuleService/GetMetrics"
	ModuleService_Scale_FullMethodName            = "/marchproxy.ModuleService/Scale"
	ModuleService_GetInstances_FullMethodName     = "/marchproxy.ModuleService/GetInstances"
	ModuleService_SetTrafficWeight_FullMethodName = "/marchproxy.ModuleService/SetTrafficWeight"
	ModuleService_GetActiveVersion_FullMethodName = "/marchproxy.ModuleService/GetActiveVersion"
	ModuleService_Rollback_FullMethodName         = "/marchproxy.ModuleService/Rollback"
	ModuleService_PromoteVersion_FullMethodName   = "/marchproxy.ModuleService/PromoteVersion"
	ModuleService_HealthCheck_FullMethodName      = "/marchproxy.ModuleService/HealthCheck"
	ModuleService_GetStats_FullMethodName         = "/marchproxy.ModuleService/GetStats"
	ModuleService_StreamMetrics_FullMethodName    = "/marchproxy.ModuleService/StreamMetrics"
	ModuleService_GetConfig_FullMethodName        = "/marchproxy.ModuleService/GetConfig"
	ModuleService_UpdateConfig_FullMethodName     = "/marchproxy.ModuleService/UpdateConfig"
)

// ModuleServiceClient is the client API for ModuleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ModuleService is the interface that all module containers (ALB, DBLB, AILB, RTMP) must implement.
// This allows the NLB to uniformly manage and communicate with all modules.
type ModuleServiceClient interface {
	// GetStatus returns the current status of the module instance
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	// Reload reloads the module configuration without restarting
	Reload(ctx context.Context, in *ReloadRequest, opts ...grpc.CallOption) (*ReloadResponse, error)
	// Shutdown gracefully shuts down the module instance
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error)
	// CanHandle checks if this module can handle the given route
	CanHandle(ctx context.Context, in *CanHandleRequest, opts ...grpc.CallOption) (*CanHandleResponse, error)
	// GetRoutes returns all routes this module is configured to handle
	GetRoutes(ctx context.Context, in *GetRoutesRequest, opts ...grpc.CallOption) (*GetRoutesResponse, error)
	// UpdateRoutes updates the routing configuration for this module
	UpdateRoutes(ctx context.Context, in *UpdateRoutesRequest, opts ...grpc.CallOption) (*UpdateRoutesResponse, error)
	// DeleteRoute removes a specific route from this module
	DeleteRoute(ctx context.Context, in *DeleteRouteRequest, opts ...grpc.CallOption) (*DeleteRouteResponse, error)
	// GetRateLimits returns current rate limiting configuration
	GetRateLimits(ctx context.Context, in *GetRateLimitsRequest, opts ...grpc.CallOption) (*GetRateLimitsResponse, error)
	// SetRateLimit configures a rate limit for a target
	SetRateLimit(ctx context.Context, in *SetRateLimitRequest, opts ...grpc.CallOption) (*SetRateLimitResponse, error)
	// RemoveRateLimit removes a rate limit configuration
	RemoveRateLimit(ctx context.Context, in *RemoveRateLimitRequest, opts ...grpc.CallOption) (*RemoveRateLimitResponse, error)
	// GetMetrics returns current metrics for this module instance
	GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error)
	// Scale adjusts the scaling configuration for this module
	Scale(ctx context.Context, in *ScaleRequest, opts ...grpc.CallOption) (*ScaleResponse, error)
	// GetInstances returns information about all instances of this module
	GetInstances(ctx context.Context, in *GetInstancesRequest, opts ...grpc.CallOption) (*GetInstancesResponse, error)
	// SetTrafficWeight sets the traffic weight for this instance (blue/green)
	SetTrafficWeight(ctx context.Context, in *SetTrafficWeightRequest, opts ...grpc.CallOption) (*SetTrafficWeightResponse, error)
	// GetActiveVersion returns the currently active version
	GetActiveVersion(ctx context.Context, in *GetActiveVersionRequest, opts ...grpc.CallOption) (*GetActiveVersionResponse, error)
	// Rollback rolls back to the previous version
	Rollback(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*RollbackResponse, error)
	// PromoteVersion promotes a version from canary to full production
	PromoteVersion(ctx context.Context, in *PromoteVersionRequest, opts ...grpc.CallOption) (*PromoteVersionResponse, error)
	// HealthCheck performs a health check on this module instance
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// GetStats returns detailed statistics for this module instance
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error)
	// StreamMetrics streams real-time metrics (server-side streaming)
	StreamMetrics(ctx context.Context, in *StreamMetricsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamMetricsResponse], error)
	// GetConfig returns the current configuration
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error)
	// UpdateConfig updates the module configuration
	UpdateConfig(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*UpdateConfigResponse, error)
}

type moduleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewModuleServiceClient(cc grpc.ClientConnInterface) ModuleServiceClient {
	return &moduleServiceClient{cc}
}

func (c *moduleServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, ModuleService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleServiceClient) Reload(ctx context.Context, in *ReloadRequest, opts ...grpc.CallOption) (*ReloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReloadResponse)
	err := c.cc.Invoke(ctx, ModuleService_Reload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleServiceClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShutdownResponse)
	err := c.cc.Invoke(ctx, ModuleService_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleServiceClient) CanHandle(ctx context.Context, in *CanHandleRequest, opts ...grpc.CallOption) (*CanHandleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CanHandleResponse)
	err := c.cc.Invoke(ctx, ModuleService_CanHandle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleServiceClient) GetRoutes(ctx context.Context, in *GetRoutesRequest, opts ...grpc.CallOption) (*GetRoutesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoutesResponse)
	err := c.cc.Invoke(ctx, ModuleService_GetRoutes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleServiceClient) UpdateRoutes(ctx context.Context, in *UpdateRoutesRequest, opts ...grpc.CallOption) (*UpdateRoutesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRoutesResponse)
	err := c.cc.Invoke(ctx, ModuleService_UpdateRoutes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleServiceClient) DeleteRoute(ctx context.Context, in *DeleteRouteRequest, opts ...grpc.CallOption) (*DeleteRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRouteResponse)
	err := c.cc.Invoke(ctx, ModuleService_DeleteRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleServiceClient) GetRateLimits(ctx context.Context, in *GetRateLimitsRequest, opts ...grpc.CallOption) (*GetRateLimitsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRateLimitsResponse)
	err := c.cc.Invoke(ctx, ModuleService_GetRateLimits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleServiceClient) SetRateLimit(ctx context.Context, in *SetRateLimitRequest, opts ...grpc.CallOption) (*SetRateLimitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetRateLimitResponse)
	err := c.cc.Invoke(ctx, ModuleService_SetRateLimit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleServiceClient) RemoveRateLimit(ctx context.Context, in *RemoveRateLimitRequest, opts ...grpc.CallOption) (*RemoveRateLimitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveRateLimitResponse)
	err := c.cc.Invoke(ctx, ModuleService_RemoveRateLimit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleServiceClient) GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMetricsResponse)
	err := c.cc.Invoke(ctx, ModuleService_GetMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleServiceClient) Scale(ctx context.Context, in *ScaleRequest, opts ...grpc.CallOption) (*ScaleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScaleResponse)
	err := c.cc.Invoke(ctx, ModuleService_Scale_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleServiceClient) GetInstances(ctx context.Context, in *GetInstancesRequest, opts ...grpc.CallOption) (*GetInstancesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInstancesResponse)
	err := c.cc.Invoke(ctx, ModuleService_GetInstances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleServiceClient) SetTrafficWeight(ctx context.Context, in *SetTrafficWeightRequest, opts ...grpc.CallOption) (*SetTrafficWeightResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetTrafficWeightResponse)
	err := c.cc.Invoke(ctx, ModuleService_SetTrafficWeight_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleServiceClient) GetActiveVersion(ctx context.Context, in *GetActiveVersionRequest, opts ...grpc.CallOption) (*GetActiveVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetActiveVersionResponse)
	err := c.cc.Invoke(ctx, ModuleService_GetActiveVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleServiceClient) Rollback(ctx context.Context, in *RollbackRequest, opts ...grpc.CallOption) (*RollbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RollbackResponse)
	err := c.cc.Invoke(ctx, ModuleService_Rollback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleServiceClient) PromoteVersion(ctx context.Context, in *PromoteVersionRequest, opts ...grpc.CallOption) (*PromoteVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PromoteVersionResponse)
	err := c.cc.Invoke(ctx, ModuleService_PromoteVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, ModuleService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleServiceClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatsResponse)
	err := c.cc.Invoke(ctx, ModuleService_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleServiceClient) StreamMetrics(ctx context.Context, in *StreamMetricsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamMetricsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ModuleService_ServiceDesc.Streams[0], ModuleService_StreamMetrics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamMetricsRequest, StreamMetricsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ModuleService_StreamMetricsClient = grpc.ServerStreamingClient[StreamMetricsResponse]

func (c *moduleServiceClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfigResponse)
	err := c.cc.Invoke(ctx, ModuleService_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moduleServiceClient) UpdateConfig(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*UpdateConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateConfigResponse)
	err := c.cc.Invoke(ctx, ModuleService_UpdateConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModuleServiceServer is the server API for ModuleService service.
// All implementations must embed UnimplementedModuleServiceServer
// for forward compatibility.
//
// ModuleService is the interface that all module containers (ALB, DBLB, AILB, RTMP) must implement.
// This allows the NLB to uniformly manage and communicate with all modules.
type ModuleServiceServer interface {
	// GetStatus returns the current status of the module instance
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	// Reload reloads the module configuration without restarting
	Reload(context.Context, *ReloadRequest) (*ReloadResponse, error)
	// Shutdown gracefully shuts down the module instance
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
	// CanHandle checks if this module can handle the given route
	CanHandle(context.Context, *CanHandleRequest) (*CanHandleResponse, error)
	// GetRoutes returns all routes this module is configured to handle
	GetRoutes(context.Context, *GetRoutesRequest) (*GetRoutesResponse, error)
	// UpdateRoutes updates the routing configuration for this module
	UpdateRoutes(context.Context, *UpdateRoutesRequest) (*UpdateRoutesResponse, error)
	// DeleteRoute removes a specific route from this module
	DeleteRoute(context.Context, *DeleteRouteRequest) (*DeleteRouteResponse, error)
	// GetRateLimits returns current rate limiting configuration
	GetRateLimits(context.Context, *GetRateLimitsRequest) (*GetRateLimitsResponse, error)
	// SetRateLimit configures a rate limit for a target
	SetRateLimit(context.Context, *SetRateLimitRequest) (*SetRateLimitResponse, error)
	// RemoveRateLimit removes a rate limit configuration
	RemoveRateLimit(context.Context, *RemoveRateLimitRequest) (*RemoveRateLimitResponse, error)
	// GetMetrics returns current metrics for this module instance
	GetMetrics(context.Context, *GetMetricsRequest) (*GetMetricsResponse, error)
	// Scale adjusts the scaling configuration for this module
	Scale(context.Context, *ScaleRequest) (*ScaleResponse, error)
	// GetInstances returns information about all instances of this module
	GetInstances(context.Context, *GetInstancesRequest) (*GetInstancesResponse, error)
	// SetTrafficWeight sets the traffic weight for this instance (blue/green)
	SetTrafficWeight(context.Context, *SetTrafficWeightRequest) (*SetTrafficWeightResponse, error)
	// GetActiveVersion returns the currently active version
	GetActiveVersion(context.Context, *GetActiveVersionRequest) (*GetActiveVersionResponse, error)
	// Rollback rolls back to the previous version
	Rollback(context.Context, *RollbackRequest) (*RollbackResponse, error)
	// PromoteVersion promotes a version from canary to full production
	PromoteVersion(context.Context, *PromoteVersionRequest) (*PromoteVersionResponse, error)
	// HealthCheck performs a health check on this module instance
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// GetStats returns detailed statistics for this module instance
	GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error)
	// StreamMetrics streams real-time metrics (server-side streaming)
	StreamMetrics(*StreamMetricsRequest, grpc.ServerStreamingServer[StreamMetricsResponse]) error
	// GetConfig returns the current configuration
	GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error)
	// UpdateConfig updates the module configuration
	UpdateConfig(context.Context, *UpdateConfigRequest) (*UpdateConfigResponse, error)
	mustEmbedUnimplementedModuleServiceServer()
}

// UnimplementedModuleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModuleServiceServer struct{}

func (UnimplementedModuleServiceServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedModuleServiceServer) Reload(context.Context, *ReloadRequest) (*ReloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reload not implemented")
}
func (UnimplementedModuleServiceServer) Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedModuleServiceServer) CanHandle(context.Context, *CanHandleRequest) (*CanHandleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CanHandle not implemented")
}
func (UnimplementedModuleServiceServer) GetRoutes(context.Context, *GetRoutesRequest) (*GetRoutesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRoutes not implemented")
}
func (UnimplementedModuleServiceServer) UpdateRoutes(context.Context, *UpdateRoutesRequest) (*UpdateRoutesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRoutes not implemented")
}
func (UnimplementedModuleServiceServer) DeleteRoute(context.Context, *DeleteRouteRequest) (*DeleteRouteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRoute not implemented")
}
func (UnimplementedModuleServiceServer) GetRateLimits(context.Context, *GetRateLimitsRequest) (*GetRateLimitsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRateLimits not implemented")
}
func (UnimplementedModuleServiceServer) SetRateLimit(context.Context, *SetRateLimitRequest) (*SetRateLimitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetRateLimit not implemented")
}
func (UnimplementedModuleServiceServer) RemoveRateLimit(context.Context, *RemoveRateLimitRequest) (*RemoveRateLimitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveRateLimit not implemented")
}
func (UnimplementedModuleServiceServer) GetMetrics(context.Context, *GetMetricsRequest) (*GetMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMetrics not implemented")
}
func (UnimplementedModuleServiceServer) Scale(context.Context, *ScaleRequest) (*ScaleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Scale not implemented")
}
func (UnimplementedModuleServiceServer) GetInstances(context.Context, *GetInstancesRequest) (*GetInstancesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInstances not implemented")
}
func (UnimplementedModuleServiceServer) SetTrafficWeight(context.Context, *SetTrafficWeightRequest) (*SetTrafficWeightResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetTrafficWeight not implemented")
}
func (UnimplementedModuleServiceServer) GetActiveVersion(context.Context, *GetActiveVersionRequest) (*GetActiveVersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActiveVersion not implemented")
}
func (UnimplementedModuleServiceServer) Rollback(context.Context, *RollbackRequest) (*RollbackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Rollback not implemented")
}
func (UnimplementedModuleServiceServer) PromoteVersion(context.Context, *PromoteVersionRequest) (*PromoteVersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PromoteVersion not implemented")
}
func (UnimplementedModuleServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedModuleServiceServer) GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedModuleServiceServer) StreamMetrics(*StreamMetricsRequest, grpc.ServerStreamingServer[StreamMetricsResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamMetrics not implemented")
}
func (UnimplementedModuleServiceServer) GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedModuleServiceServer) UpdateConfig(context.Context, *UpdateConfigRequest) (*UpdateConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateConfig not implemented")
}
func (UnimplementedModuleServiceServer) mustEmbedUnimplementedModuleServiceServer() {}
func (UnimplementedModuleServiceServer) testEmbeddedByValue()                       {}

// UnsafeModuleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModuleServiceServer will
// result in compilation errors.
type UnsafeModuleServiceServer interface {
	mustEmbedUnimplementedModuleServiceServer()
}

func RegisterModuleServiceServer(s grpc.ServiceRegistrar, srv ModuleServiceServer) {
	// If the following call panics, it indicates UnimplementedModuleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ModuleService_ServiceDesc, srv)
}

func _ModuleService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModuleService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleService_Reload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServiceServer).Reload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModuleService_Reload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServiceServer).Reload(ctx, req.(*ReloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleService_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServiceServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModuleService_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServiceServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleService_CanHandle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CanHandleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServiceServer).CanHandle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModuleService_CanHandle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServiceServer).CanHandle(ctx, req.(*CanHandleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleService_GetRoutes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoutesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServiceServer).GetRoutes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModuleService_GetRoutes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServiceServer).GetRoutes(ctx, req.(*GetRoutesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleService_UpdateRoutes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRoutesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServiceServer).UpdateRoutes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModuleService_UpdateRoutes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServiceServer).UpdateRoutes(ctx, req.(*UpdateRoutesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleService_DeleteRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServiceServer).DeleteRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModuleService_DeleteRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServiceServer).DeleteRoute(ctx, req.(*DeleteRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleService_GetRateLimits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRateLimitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServiceServer).GetRateLimits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModuleService_GetRateLimits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServiceServer).GetRateLimits(ctx, req.(*GetRateLimitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleService_SetRateLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRateLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServiceServer).SetRateLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModuleService_SetRateLimit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServiceServer).SetRateLimit(ctx, req.(*SetRateLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleService_RemoveRateLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRateLimitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServiceServer).RemoveRateLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModuleService_RemoveRateLimit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServiceServer).RemoveRateLimit(ctx, req.(*RemoveRateLimitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleService_GetMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServiceServer).GetMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModuleService_GetMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServiceServer).GetMetrics(ctx, req.(*GetMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleService_Scale_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScaleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServiceServer).Scale(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModuleService_Scale_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServiceServer).Scale(ctx, req.(*ScaleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleService_GetInstances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServiceServer).GetInstances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModuleService_GetInstances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServiceServer).GetInstances(ctx, req.(*GetInstancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleService_SetTrafficWeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTrafficWeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServiceServer).SetTrafficWeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModuleService_SetTrafficWeight_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServiceServer).SetTrafficWeight(ctx, req.(*SetTrafficWeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleService_GetActiveVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActiveVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServiceServer).GetActiveVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModuleService_GetActiveVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServiceServer).GetActiveVersion(ctx, req.(*GetActiveVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleService_Rollback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServiceServer).Rollback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModuleService_Rollback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServiceServer).Rollback(ctx, req.(*RollbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleService_PromoteVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromoteVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServiceServer).PromoteVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModuleService_PromoteVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServiceServer).PromoteVersion(ctx, req.(*PromoteVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModuleService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModuleService_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServiceServer).GetStats(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleService_StreamMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamMetricsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ModuleServiceServer).StreamMetrics(m, &grpc.GenericServerStream[StreamMetricsRequest, StreamMetricsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ModuleService_StreamMetricsServer = grpc.ServerStreamingServer[StreamMetricsResponse]

func _ModuleService_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServiceServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModuleService_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServiceServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModuleService_UpdateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModuleServiceServer).UpdateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModuleService_UpdateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModuleServiceServer).UpdateConfig(ctx, req.(*UpdateConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ModuleService_ServiceDesc is the grpc.ServiceDesc for ModuleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModuleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "marchproxy.ModuleService",
	HandlerType: (*ModuleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _ModuleService_GetStatus_Handler,
		},
		{
			MethodName: "Reload",
			Handler:    _ModuleService_Reload_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _ModuleService_Shutdown_Handler,
		},
		{
			MethodName: "CanHandle",
			Handler:    _ModuleService_CanHandle_Handler,
		},
		{
			MethodName: "GetRoutes",
			Handler:    _ModuleService_GetRoutes_Handler,
		},
		{
			MethodName: "UpdateRoutes",
			Handler:    _ModuleService_UpdateRoutes_Handler,
		},
		{
			MethodName: "DeleteRoute",
			Handler:    _ModuleService_DeleteRoute_Handler,
		},
		{
			MethodName: "GetRateLimits",
			Handler:    _ModuleService_GetRateLimits_Handler,
		},
		{
			MethodName: "SetRateLimit",
			Handler:    _ModuleService_SetRateLimit_Handler,
		},
		{
			MethodName: "RemoveRateLimit",
			Handler:    _ModuleService_RemoveRateLimit_Handler,
		},
		{
			MethodName: "GetMetrics",
			Handler:    _ModuleService_GetMetrics_Handler,
		},
		{
			MethodName: "Scale",
			Handler:    _ModuleService_Scale_Handler,
		},
		{
			MethodName: "GetInstances",
			Handler:    _ModuleService_GetInstances_Handler,
		},
		{
			MethodName: "SetTrafficWeight",
			Handler:    _ModuleService_SetTrafficWeight_Handler,
		},
		{
			MethodName: "GetActiveVersion",
			Handler:    _ModuleService_GetActiveVersion_Handler,
		},
		{
			MethodName: "Rollback",
			Handler:    _ModuleService_Rollback_Handler,
		},
		{
			MethodName: "PromoteVersion",
			Handler:    _ModuleService_PromoteVersion_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _ModuleService_HealthCheck_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _ModuleService_GetStats_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _ModuleService_GetConfig_Handler,
		},
		{
			MethodName: "UpdateConfig",
			Handler:    _ModuleService_UpdateConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMetrics",
			Handler:       _ModuleService_StreamMetrics_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "marchproxy/module.proto",
}
