// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: marchproxy/nlb.proto

package marchproxy

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NLBService_RegisterModule_FullMethodName      = "/marchproxy.NLBService/RegisterModule"
	NLBService_UnregisterModule_FullMethodName    = "/marchproxy.NLBService/UnregisterModule"
	NLBService_Heartbeat_FullMethodName           = "/marchproxy.NLBService/Heartbeat"
	NLBService_ListModules_FullMethodName         = "/marchproxy.NLBService/ListModules"
	NLBService_GetModuleInfo_FullMethodName       = "/marchproxy.NLBService/GetModuleInfo"
	NLBService_UpdateRouting_FullMethodName       = "/marchproxy.NLBService/UpdateRouting"
	NLBService_GetRoutingTable_FullMethodName     = "/marchproxy.NLBService/GetRoutingTable"
	NLBService_RouteRequest_FullMethodName        = "/marchproxy.NLBService/RouteRequest"
	NLBService_ValidateRoute_FullMethodName       = "/marchproxy.NLBService/ValidateRoute"
	NLBService_ReportMetrics_FullMethodName       = "/marchproxy.NLBService/ReportMetrics"
	NLBService_GetNLBMetrics_FullMethodName       = "/marchproxy.NLBService/GetNLBMetrics"
	NLBService_GetModuleMetrics_FullMethodName    = "/marchproxy.NLBService/GetModuleMetrics"
	NLBService_StreamNLBMetrics_FullMethodName    = "/marchproxy.NLBService/StreamNLBMetrics"
	NLBService_CheckHealth_FullMethodName         = "/marchproxy.NLBService/CheckHealth"
	NLBService_GetNLBStatus_FullMethodName        = "/marchproxy.NLBService/GetNLBStatus"
	NLBService_UpdateNLBConfig_FullMethodName     = "/marchproxy.NLBService/UpdateNLBConfig"
	NLBService_GetNLBConfig_FullMethodName        = "/marchproxy.NLBService/GetNLBConfig"
	NLBService_RebalanceLoad_FullMethodName       = "/marchproxy.NLBService/RebalanceLoad"
	NLBService_GetLoadDistribution_FullMethodName = "/marchproxy.NLBService/GetLoadDistribution"
	NLBService_TriggerScaling_FullMethodName      = "/marchproxy.NLBService/TriggerScaling"
)

// NLBServiceClient is the client API for NLBService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NLBService is the service that the NLB container provides for module registration,
// routing updates, and metrics reporting.
type NLBServiceClient interface {
	// RegisterModule registers a new module instance with the NLB
	RegisterModule(ctx context.Context, in *RegisterModuleRequest, opts ...grpc.CallOption) (*RegisterModuleResponse, error)
	// UnregisterModule removes a module instance from the NLB
	UnregisterModule(ctx context.Context, in *UnregisterModuleRequest, opts ...grpc.CallOption) (*UnregisterModuleResponse, error)
	// Heartbeat sends periodic heartbeat from module to NLB
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// ListModules returns all registered modules
	ListModules(ctx context.Context, in *ListModulesRequest, opts ...grpc.CallOption) (*ListModulesResponse, error)
	// GetModuleInfo returns detailed information about a specific module
	GetModuleInfo(ctx context.Context, in *GetModuleInfoRequest, opts ...grpc.CallOption) (*GetModuleInfoResponse, error)
	// UpdateRouting updates the routing configuration for the NLB
	UpdateRouting(ctx context.Context, in *UpdateRoutingRequest, opts ...grpc.CallOption) (*UpdateRoutingResponse, error)
	// GetRoutingTable returns the current routing table
	GetRoutingTable(ctx context.Context, in *GetRoutingTableRequest, opts ...grpc.CallOption) (*GetRoutingTableResponse, error)
	// RouteRequest routes a single request to the appropriate module
	RouteRequest(ctx context.Context, in *RouteRequestRequest, opts ...grpc.CallOption) (*RouteRequestResponse, error)
	// ValidateRoute validates if a route can be handled
	ValidateRoute(ctx context.Context, in *ValidateRouteRequest, opts ...grpc.CallOption) (*ValidateRouteResponse, error)
	// ReportMetrics allows modules to report metrics to the NLB
	ReportMetrics(ctx context.Context, in *ReportMetricsRequest, opts ...grpc.CallOption) (*ReportMetricsResponse, error)
	// GetNLBMetrics returns aggregated NLB metrics
	GetNLBMetrics(ctx context.Context, in *GetNLBMetricsRequest, opts ...grpc.CallOption) (*GetNLBMetricsResponse, error)
	// GetModuleMetrics returns metrics for a specific module
	GetModuleMetrics(ctx context.Context, in *GetModuleMetricsRequest, opts ...grpc.CallOption) (*GetModuleMetricsResponse, error)
	// StreamNLBMetrics streams real-time NLB metrics (server-side streaming)
	StreamNLBMetrics(ctx context.Context, in *StreamNLBMetricsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamNLBMetricsResponse], error)
	// CheckHealth performs health check on the NLB
	CheckHealth(ctx context.Context, in *CheckHealthRequest, opts ...grpc.CallOption) (*CheckHealthResponse, error)
	// GetNLBStatus returns current NLB status
	GetNLBStatus(ctx context.Context, in *GetNLBStatusRequest, opts ...grpc.CallOption) (*GetNLBStatusResponse, error)
	// UpdateNLBConfig updates the NLB configuration
	UpdateNLBConfig(ctx context.Context, in *UpdateNLBConfigRequest, opts ...grpc.CallOption) (*UpdateNLBConfigResponse, error)
	// GetNLBConfig returns the current NLB configuration
	GetNLBConfig(ctx context.Context, in *GetNLBConfigRequest, opts ...grpc.CallOption) (*GetNLBConfigResponse, error)
	// RebalanceLoad triggers load rebalancing across modules
	RebalanceLoad(ctx context.Context, in *RebalanceLoadRequest, opts ...grpc.CallOption) (*RebalanceLoadResponse, error)
	// GetLoadDistribution returns current load distribution across modules
	GetLoadDistribution(ctx context.Context, in *GetLoadDistributionRequest, opts ...grpc.CallOption) (*GetLoadDistributionResponse, error)
	// TriggerScaling triggers scaling operations for a module
	TriggerScaling(ctx context.Context, in *TriggerScalingRequest, opts ...grpc.CallOption) (*TriggerScalingResponse, error)
}

type nLBServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNLBServiceClient(cc grpc.ClientConnInterface) NLBServiceClient {
	return &nLBServiceClient{cc}
}

func (c *nLBServiceClient) RegisterModule(ctx context.Context, in *RegisterModuleRequest, opts ...grpc.CallOption) (*RegisterModuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterModuleResponse)
	err := c.cc.Invoke(ctx, NLBService_RegisterModule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nLBServiceClient) UnregisterModule(ctx context.Context, in *UnregisterModuleRequest, opts ...grpc.CallOption) (*UnregisterModuleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnregisterModuleResponse)
	err := c.cc.Invoke(ctx, NLBService_UnregisterModule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nLBServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, NLBService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nLBServiceClient) ListModules(ctx context.Context, in *ListModulesRequest, opts ...grpc.CallOption) (*ListModulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModulesResponse)
	err := c.cc.Invoke(ctx, NLBService_ListModules_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nLBServiceClient) GetModuleInfo(ctx context.Context, in *GetModuleInfoRequest, opts ...grpc.CallOption) (*GetModuleInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetModuleInfoResponse)
	err := c.cc.Invoke(ctx, NLBService_GetModuleInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nLBServiceClient) UpdateRouting(ctx context.Context, in *UpdateRoutingRequest, opts ...grpc.CallOption) (*UpdateRoutingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRoutingResponse)
	err := c.cc.Invoke(ctx, NLBService_UpdateRouting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nLBServiceClient) GetRoutingTable(ctx context.Context, in *GetRoutingTableRequest, opts ...grpc.CallOption) (*GetRoutingTableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoutingTableResponse)
	err := c.cc.Invoke(ctx, NLBService_GetRoutingTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nLBServiceClient) RouteRequest(ctx context.Context, in *RouteRequestRequest, opts ...grpc.CallOption) (*RouteRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RouteRequestResponse)
	err := c.cc.Invoke(ctx, NLBService_RouteRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nLBServiceClient) ValidateRoute(ctx context.Context, in *ValidateRouteRequest, opts ...grpc.CallOption) (*ValidateRouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateRouteResponse)
	err := c.cc.Invoke(ctx, NLBService_ValidateRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nLBServiceClient) ReportMetrics(ctx context.Context, in *ReportMetricsRequest, opts ...grpc.CallOption) (*ReportMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportMetricsResponse)
	err := c.cc.Invoke(ctx, NLBService_ReportMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nLBServiceClient) GetNLBMetrics(ctx context.Context, in *GetNLBMetricsRequest, opts ...grpc.CallOption) (*GetNLBMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNLBMetricsResponse)
	err := c.cc.Invoke(ctx, NLBService_GetNLBMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nLBServiceClient) GetModuleMetrics(ctx context.Context, in *GetModuleMetricsRequest, opts ...grpc.CallOption) (*GetModuleMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetModuleMetricsResponse)
	err := c.cc.Invoke(ctx, NLBService_GetModuleMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nLBServiceClient) StreamNLBMetrics(ctx context.Context, in *StreamNLBMetricsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamNLBMetricsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NLBService_ServiceDesc.Streams[0], NLBService_StreamNLBMetrics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamNLBMetricsRequest, StreamNLBMetricsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NLBService_StreamNLBMetricsClient = grpc.ServerStreamingClient[StreamNLBMetricsResponse]

func (c *nLBServiceClient) CheckHealth(ctx context.Context, in *CheckHealthRequest, opts ...grpc.CallOption) (*CheckHealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckHealthResponse)
	err := c.cc.Invoke(ctx, NLBService_CheckHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nLBServiceClient) GetNLBStatus(ctx context.Context, in *GetNLBStatusRequest, opts ...grpc.CallOption) (*GetNLBStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNLBStatusResponse)
	err := c.cc.Invoke(ctx, NLBService_GetNLBStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nLBServiceClient) UpdateNLBConfig(ctx context.Context, in *UpdateNLBConfigRequest, opts ...grpc.CallOption) (*UpdateNLBConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateNLBConfigResponse)
	err := c.cc.Invoke(ctx, NLBService_UpdateNLBConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nLBServiceClient) GetNLBConfig(ctx context.Context, in *GetNLBConfigRequest, opts ...grpc.CallOption) (*GetNLBConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNLBConfigResponse)
	err := c.cc.Invoke(ctx, NLBService_GetNLBConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nLBServiceClient) RebalanceLoad(ctx context.Context, in *RebalanceLoadRequest, opts ...grpc.CallOption) (*RebalanceLoadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RebalanceLoadResponse)
	err := c.cc.Invoke(ctx, NLBService_RebalanceLoad_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nLBServiceClient) GetLoadDistribution(ctx context.Context, in *GetLoadDistributionRequest, opts ...grpc.CallOption) (*GetLoadDistributionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLoadDistributionResponse)
	err := c.cc.Invoke(ctx, NLBService_GetLoadDistribution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nLBServiceClient) TriggerScaling(ctx context.Context, in *TriggerScalingRequest, opts ...grpc.CallOption) (*TriggerScalingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerScalingResponse)
	err := c.cc.Invoke(ctx, NLBService_TriggerScaling_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NLBServiceServer is the server API for NLBService service.
// All implementations must embed UnimplementedNLBServiceServer
// for forward compatibility.
//
// NLBService is the service that the NLB container provides for module registration,
// routing updates, and metrics reporting.
type NLBServiceServer interface {
	// RegisterModule registers a new module instance with the NLB
	RegisterModule(context.Context, *RegisterModuleRequest) (*RegisterModuleResponse, error)
	// UnregisterModule removes a module instance from the NLB
	UnregisterModule(context.Context, *UnregisterModuleRequest) (*UnregisterModuleResponse, error)
	// Heartbeat sends periodic heartbeat from module to NLB
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// ListModules returns all registered modules
	ListModules(context.Context, *ListModulesRequest) (*ListModulesResponse, error)
	// GetModuleInfo returns detailed information about a specific module
	GetModuleInfo(context.Context, *GetModuleInfoRequest) (*GetModuleInfoResponse, error)
	// UpdateRouting updates the routing configuration for the NLB
	UpdateRouting(context.Context, *UpdateRoutingRequest) (*UpdateRoutingResponse, error)
	// GetRoutingTable returns the current routing table
	GetRoutingTable(context.Context, *GetRoutingTableRequest) (*GetRoutingTableResponse, error)
	// RouteRequest routes a single request to the appropriate module
	RouteRequest(context.Context, *RouteRequestRequest) (*RouteRequestResponse, error)
	// ValidateRoute validates if a route can be handled
	ValidateRoute(context.Context, *ValidateRouteRequest) (*ValidateRouteResponse, error)
	// ReportMetrics allows modules to report metrics to the NLB
	ReportMetrics(context.Context, *ReportMetricsRequest) (*ReportMetricsResponse, error)
	// GetNLBMetrics returns aggregated NLB metrics
	GetNLBMetrics(context.Context, *GetNLBMetricsRequest) (*GetNLBMetricsResponse, error)
	// GetModuleMetrics returns metrics for a specific module
	GetModuleMetrics(context.Context, *GetModuleMetricsRequest) (*GetModuleMetricsResponse, error)
	// StreamNLBMetrics streams real-time NLB metrics (server-side streaming)
	StreamNLBMetrics(*StreamNLBMetricsRequest, grpc.ServerStreamingServer[StreamNLBMetricsResponse]) error
	// CheckHealth performs health check on the NLB
	CheckHealth(context.Context, *CheckHealthRequest) (*CheckHealthResponse, error)
	// GetNLBStatus returns current NLB status
	GetNLBStatus(context.Context, *GetNLBStatusRequest) (*GetNLBStatusResponse, error)
	// UpdateNLBConfig updates the NLB configuration
	UpdateNLBConfig(context.Context, *UpdateNLBConfigRequest) (*UpdateNLBConfigResponse, error)
	// GetNLBConfig returns the current NLB configuration
	GetNLBConfig(context.Context, *GetNLBConfigRequest) (*GetNLBConfigResponse, error)
	// RebalanceLoad triggers load rebalancing across modules
	RebalanceLoad(context.Context, *RebalanceLoadRequest) (*RebalanceLoadResponse, error)
	// GetLoadDistribution returns current load distribution across modules
	GetLoadDistribution(context.Context, *GetLoadDistributionRequest) (*GetLoadDistributionResponse, error)
	// TriggerScaling triggers scaling operations for a module
	TriggerScaling(context.Context, *TriggerScalingRequest) (*TriggerScalingResponse, error)
	mustEmbedUnimplementedNLBServiceServer()
}

// UnimplementedNLBServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNLBServiceServer struct{}

func (UnimplementedNLBServiceServer) RegisterModule(context.Context, *RegisterModuleRequest) (*RegisterModuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterModule not implemented")
}
func (UnimplementedNLBServiceServer) UnregisterModule(context.Context, *UnregisterModuleRequest) (*UnregisterModuleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnregisterModule not implemented")
}
func (UnimplementedNLBServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedNLBServiceServer) ListModules(context.Context, *ListModulesRequest) (*ListModulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModules not implemented")
}
func (UnimplementedNLBServiceServer) GetModuleInfo(context.Context, *GetModuleInfoRequest) (*GetModuleInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetModuleInfo not implemented")
}
func (UnimplementedNLBServiceServer) UpdateRouting(context.Context, *UpdateRoutingRequest) (*UpdateRoutingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRouting not implemented")
}
func (UnimplementedNLBServiceServer) GetRoutingTable(context.Context, *GetRoutingTableRequest) (*GetRoutingTableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRoutingTable not implemented")
}
func (UnimplementedNLBServiceServer) RouteRequest(context.Context, *RouteRequestRequest) (*RouteRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RouteRequest not implemented")
}
func (UnimplementedNLBServiceServer) ValidateRoute(context.Context, *ValidateRouteRequest) (*ValidateRouteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateRoute not implemented")
}
func (UnimplementedNLBServiceServer) ReportMetrics(context.Context, *ReportMetricsRequest) (*ReportMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportMetrics not implemented")
}
func (UnimplementedNLBServiceServer) GetNLBMetrics(context.Context, *GetNLBMetricsRequest) (*GetNLBMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNLBMetrics not implemented")
}
func (UnimplementedNLBServiceServer) GetModuleMetrics(context.Context, *GetModuleMetricsRequest) (*GetModuleMetricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetModuleMetrics not implemented")
}
func (UnimplementedNLBServiceServer) StreamNLBMetrics(*StreamNLBMetricsRequest, grpc.ServerStreamingServer[StreamNLBMetricsResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamNLBMetrics not implemented")
}
func (UnimplementedNLBServiceServer) CheckHealth(context.Context, *CheckHealthRequest) (*CheckHealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckHealth not implemented")
}
func (UnimplementedNLBServiceServer) GetNLBStatus(context.Context, *GetNLBStatusRequest) (*GetNLBStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNLBStatus not implemented")
}
func (UnimplementedNLBServiceServer) UpdateNLBConfig(context.Context, *UpdateNLBConfigRequest) (*UpdateNLBConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateNLBConfig not implemented")
}
func (UnimplementedNLBServiceServer) GetNLBConfig(context.Context, *GetNLBConfigRequest) (*GetNLBConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNLBConfig not implemented")
}
func (UnimplementedNLBServiceServer) RebalanceLoad(context.Context, *RebalanceLoadRequest) (*RebalanceLoadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RebalanceLoad not implemented")
}
func (UnimplementedNLBServiceServer) GetLoadDistribution(context.Context, *GetLoadDistributionRequest) (*GetLoadDistributionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLoadDistribution not implemented")
}
func (UnimplementedNLBServiceServer) TriggerScaling(context.Context, *TriggerScalingRequest) (*TriggerScalingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerScaling not implemented")
}
func (UnimplementedNLBServiceServer) mustEmbedUnimplementedNLBServiceServer() {}
func (UnimplementedNLBServiceServer) testEmbeddedByValue()                    {}

// UnsafeNLBServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NLBServiceServer will
// result in compilation errors.
type UnsafeNLBServiceServer interface {
	mustEmbedUnimplementedNLBServiceServer()
}

func RegisterNLBServiceServer(s grpc.ServiceRegistrar, srv NLBServiceServer) {
	// If the following call panics, it indicates UnimplementedNLBServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NLBService_ServiceDesc, srv)
}

func _NLBService_RegisterModule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterModuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NLBServiceServer).RegisterModule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NLBService_RegisterModule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NLBServiceServer).RegisterModule(ctx, req.(*RegisterModuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NLBService_UnregisterModule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterModuleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NLBServiceServer).UnregisterModule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NLBService_UnregisterModule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NLBServiceServer).UnregisterModule(ctx, req.(*UnregisterModuleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NLBService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NLBServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NLBService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NLBServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NLBService_ListModules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NLBServiceServer).ListModules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NLBService_ListModules_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NLBServiceServer).ListModules(ctx, req.(*ListModulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NLBService_GetModuleInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModuleInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NLBServiceServer).GetModuleInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NLBService_GetModuleInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NLBServiceServer).GetModuleInfo(ctx, req.(*GetModuleInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NLBService_UpdateRouting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRoutingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NLBServiceServer).UpdateRouting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NLBService_UpdateRouting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NLBServiceServer).UpdateRouting(ctx, req.(*UpdateRoutingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NLBService_GetRoutingTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoutingTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NLBServiceServer).GetRoutingTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NLBService_GetRoutingTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NLBServiceServer).GetRoutingTable(ctx, req.(*GetRoutingTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NLBService_RouteRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NLBServiceServer).RouteRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NLBService_RouteRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NLBServiceServer).RouteRequest(ctx, req.(*RouteRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NLBService_ValidateRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NLBServiceServer).ValidateRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NLBService_ValidateRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NLBServiceServer).ValidateRoute(ctx, req.(*ValidateRouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NLBService_ReportMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NLBServiceServer).ReportMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NLBService_ReportMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NLBServiceServer).ReportMetrics(ctx, req.(*ReportMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NLBService_GetNLBMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNLBMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NLBServiceServer).GetNLBMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NLBService_GetNLBMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NLBServiceServer).GetNLBMetrics(ctx, req.(*GetNLBMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NLBService_GetModuleMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModuleMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NLBServiceServer).GetModuleMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NLBService_GetModuleMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NLBServiceServer).GetModuleMetrics(ctx, req.(*GetModuleMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NLBService_StreamNLBMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamNLBMetricsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NLBServiceServer).StreamNLBMetrics(m, &grpc.GenericServerStream[StreamNLBMetricsRequest, StreamNLBMetricsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NLBService_StreamNLBMetricsServer = grpc.ServerStreamingServer[StreamNLBMetricsResponse]

func _NLBService_CheckHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NLBServiceServer).CheckHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NLBService_CheckHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NLBServiceServer).CheckHealth(ctx, req.(*CheckHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NLBService_GetNLBStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNLBStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NLBServiceServer).GetNLBStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NLBService_GetNLBStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NLBServiceServer).GetNLBStatus(ctx, req.(*GetNLBStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NLBService_UpdateNLBConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNLBConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NLBServiceServer).UpdateNLBConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NLBService_UpdateNLBConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NLBServiceServer).UpdateNLBConfig(ctx, req.(*UpdateNLBConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NLBService_GetNLBConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNLBConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NLBServiceServer).GetNLBConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NLBService_GetNLBConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NLBServiceServer).GetNLBConfig(ctx, req.(*GetNLBConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NLBService_RebalanceLoad_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RebalanceLoadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NLBServiceServer).RebalanceLoad(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NLBService_RebalanceLoad_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NLBServiceServer).RebalanceLoad(ctx, req.(*RebalanceLoadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NLBService_GetLoadDistribution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLoadDistributionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NLBServiceServer).GetLoadDistribution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NLBService_GetLoadDistribution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NLBServiceServer).GetLoadDistribution(ctx, req.(*GetLoadDistributionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NLBService_TriggerScaling_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerScalingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NLBServiceServer).TriggerScaling(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NLBService_TriggerScaling_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NLBServiceServer).TriggerScaling(ctx, req.(*TriggerScalingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NLBService_ServiceDesc is the grpc.ServiceDesc for NLBService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NLBService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "marchproxy.NLBService",
	HandlerType: (*NLBServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterModule",
			Handler:    _NLBService_RegisterModule_Handler,
		},
		{
			MethodName: "UnregisterModule",
			Handler:    _NLBService_UnregisterModule_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _NLBService_Heartbeat_Handler,
		},
		{
			MethodName: "ListModules",
			Handler:    _NLBService_ListModules_Handler,
		},
		{
			MethodName: "GetModuleInfo",
			Handler:    _NLBService_GetModuleInfo_Handler,
		},
		{
			MethodName: "UpdateRouting",
			Handler:    _NLBService_UpdateRouting_Handler,
		},
		{
			MethodName: "GetRoutingTable",
			Handler:    _NLBService_GetRoutingTable_Handler,
		},
		{
			MethodName: "RouteRequest",
			Handler:    _NLBService_RouteRequest_Handler,
		},
		{
			MethodName: "ValidateRoute",
			Handler:    _NLBService_ValidateRoute_Handler,
		},
		{
			MethodName: "ReportMetrics",
			Handler:    _NLBService_ReportMetrics_Handler,
		},
		{
			MethodName: "GetNLBMetrics",
			Handler:    _NLBService_GetNLBMetrics_Handler,
		},
		{
			MethodName: "GetModuleMetrics",
			Handler:    _NLBService_GetModuleMetrics_Handler,
		},
		{
			MethodName: "CheckHealth",
			Handler:    _NLBService_CheckHealth_Handler,
		},
		{
			MethodName: "GetNLBStatus",
			Handler:    _NLBService_GetNLBStatus_Handler,
		},
		{
			MethodName: "UpdateNLBConfig",
			Handler:    _NLBService_UpdateNLBConfig_Handler,
		},
		{
			MethodName: "GetNLBConfig",
			Handler:    _NLBService_GetNLBConfig_Handler,
		},
		{
			MethodName: "RebalanceLoad",
			Handler:    _NLBService_RebalanceLoad_Handler,
		},
		{
			MethodName: "GetLoadDistribution",
			Handler:    _NLBService_GetLoadDistribution_Handler,
		},
		{
			MethodName: "TriggerScaling",
			Handler:    _NLBService_TriggerScaling_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamNLBMetrics",
			Handler:       _NLBService_StreamNLBMetrics_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "marchproxy/nlb.proto",
}
