// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: marchproxy/waddleai.proto

package marchproxy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	ToolType      string                 `protobuf:"bytes,2,opt,name=tool_type,json=toolType,proto3" json:"tool_type,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Region        string                 `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteRequest) Reset() {
	*x = RouteRequest{}
	mi := &file_marchproxy_waddleai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteRequest) ProtoMessage() {}

func (x *RouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marchproxy_waddleai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteRequest.ProtoReflect.Descriptor instead.
func (*RouteRequest) Descriptor() ([]byte, []int) {
	return file_marchproxy_waddleai_proto_rawDescGZIP(), []int{0}
}

func (x *RouteRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *RouteRequest) GetToolType() string {
	if x != nil {
		return x.ToolType
	}
	return ""
}

func (x *RouteRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RouteRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RouteRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *RouteRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type RouteResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RecommendedModel string                 `protobuf:"bytes,1,opt,name=recommended_model,json=recommendedModel,proto3" json:"recommended_model,omitempty"`
	Complexity       string                 `protobuf:"bytes,2,opt,name=complexity,proto3" json:"complexity,omitempty"`
	TargetType       string                 `protobuf:"bytes,3,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	Confidence       float32                `protobuf:"fixed32,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Reasoning        string                 `protobuf:"bytes,5,opt,name=reasoning,proto3" json:"reasoning,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RouteResponse) Reset() {
	*x = RouteResponse{}
	mi := &file_marchproxy_waddleai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteResponse) ProtoMessage() {}

func (x *RouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marchproxy_waddleai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteResponse.ProtoReflect.Descriptor instead.
func (*RouteResponse) Descriptor() ([]byte, []int) {
	return file_marchproxy_waddleai_proto_rawDescGZIP(), []int{1}
}

func (x *RouteResponse) GetRecommendedModel() string {
	if x != nil {
		return x.RecommendedModel
	}
	return ""
}

func (x *RouteResponse) GetComplexity() string {
	if x != nil {
		return x.Complexity
	}
	return ""
}

func (x *RouteResponse) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *RouteResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *RouteResponse) GetReasoning() string {
	if x != nil {
		return x.Reasoning
	}
	return ""
}

type SecurityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawCommand    string                 `protobuf:"bytes,1,opt,name=raw_command,json=rawCommand,proto3" json:"raw_command,omitempty"`
	ToolType      string                 `protobuf:"bytes,2,opt,name=tool_type,json=toolType,proto3" json:"tool_type,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Context       map[string]string      `protobuf:"bytes,4,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityRequest) Reset() {
	*x = SecurityRequest{}
	mi := &file_marchproxy_waddleai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityRequest) ProtoMessage() {}

func (x *SecurityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marchproxy_waddleai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityRequest.ProtoReflect.Descriptor instead.
func (*SecurityRequest) Descriptor() ([]byte, []int) {
	return file_marchproxy_waddleai_proto_rawDescGZIP(), []int{2}
}

func (x *SecurityRequest) GetRawCommand() string {
	if x != nil {
		return x.RawCommand
	}
	return ""
}

func (x *SecurityRequest) GetToolType() string {
	if x != nil {
		return x.ToolType
	}
	return ""
}

func (x *SecurityRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SecurityRequest) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

type SecurityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Safe          bool                   `protobuf:"varint,1,opt,name=safe,proto3" json:"safe,omitempty"`
	RiskScore     float32                `protobuf:"fixed32,2,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	ThreatType    string                 `protobuf:"bytes,3,opt,name=threat_type,json=threatType,proto3" json:"threat_type,omitempty"`
	Explanation   string                 `protobuf:"bytes,4,opt,name=explanation,proto3" json:"explanation,omitempty"`
	Blocked       bool                   `protobuf:"varint,5,opt,name=blocked,proto3" json:"blocked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityResponse) Reset() {
	*x = SecurityResponse{}
	mi := &file_marchproxy_waddleai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityResponse) ProtoMessage() {}

func (x *SecurityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marchproxy_waddleai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityResponse.ProtoReflect.Descriptor instead.
func (*SecurityResponse) Descriptor() ([]byte, []int) {
	return file_marchproxy_waddleai_proto_rawDescGZIP(), []int{3}
}

func (x *SecurityResponse) GetSafe() bool {
	if x != nil {
		return x.Safe
	}
	return false
}

func (x *SecurityResponse) GetRiskScore() float32 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *SecurityResponse) GetThreatType() string {
	if x != nil {
		return x.ThreatType
	}
	return ""
}

func (x *SecurityResponse) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

func (x *SecurityResponse) GetBlocked() bool {
	if x != nil {
		return x.Blocked
	}
	return false
}

type StoreTurnRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SessionId         string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId            string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserMessage       string                 `protobuf:"bytes,3,opt,name=user_message,json=userMessage,proto3" json:"user_message,omitempty"`
	AssistantResponse string                 `protobuf:"bytes,4,opt,name=assistant_response,json=assistantResponse,proto3" json:"assistant_response,omitempty"`
	Model             string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	Provider          string                 `protobuf:"bytes,6,opt,name=provider,proto3" json:"provider,omitempty"`
	Metadata          map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StoreTurnRequest) Reset() {
	*x = StoreTurnRequest{}
	mi := &file_marchproxy_waddleai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreTurnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreTurnRequest) ProtoMessage() {}

func (x *StoreTurnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marchproxy_waddleai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreTurnRequest.ProtoReflect.Descriptor instead.
func (*StoreTurnRequest) Descriptor() ([]byte, []int) {
	return file_marchproxy_waddleai_proto_rawDescGZIP(), []int{4}
}

func (x *StoreTurnRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StoreTurnRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StoreTurnRequest) GetUserMessage() string {
	if x != nil {
		return x.UserMessage
	}
	return ""
}

func (x *StoreTurnRequest) GetAssistantResponse() string {
	if x != nil {
		return x.AssistantResponse
	}
	return ""
}

func (x *StoreTurnRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *StoreTurnRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *StoreTurnRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type StoreTurnResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreTurnResponse) Reset() {
	*x = StoreTurnResponse{}
	mi := &file_marchproxy_waddleai_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreTurnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreTurnResponse) ProtoMessage() {}

func (x *StoreTurnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marchproxy_waddleai_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreTurnResponse.ProtoReflect.Descriptor instead.
func (*StoreTurnResponse) Descriptor() ([]byte, []int) {
	return file_marchproxy_waddleai_proto_rawDescGZIP(), []int{5}
}

func (x *StoreTurnResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContextRequest) Reset() {
	*x = GetContextRequest{}
	mi := &file_marchproxy_waddleai_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContextRequest) ProtoMessage() {}

func (x *GetContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marchproxy_waddleai_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContextRequest.ProtoReflect.Descriptor instead.
func (*GetContextRequest) Descriptor() ([]byte, []int) {
	return file_marchproxy_waddleai_proto_rawDescGZIP(), []int{6}
}

func (x *GetContextRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetContextRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetContextRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetContextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memories      []*MemoryEntry         `protobuf:"bytes,1,rep,name=memories,proto3" json:"memories,omitempty"`
	Summary       string                 `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContextResponse) Reset() {
	*x = GetContextResponse{}
	mi := &file_marchproxy_waddleai_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContextResponse) ProtoMessage() {}

func (x *GetContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marchproxy_waddleai_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContextResponse.ProtoReflect.Descriptor instead.
func (*GetContextResponse) Descriptor() ([]byte, []int) {
	return file_marchproxy_waddleai_proto_rawDescGZIP(), []int{7}
}

func (x *GetContextResponse) GetMemories() []*MemoryEntry {
	if x != nil {
		return x.Memories
	}
	return nil
}

func (x *GetContextResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

type SearchMemoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Threshold     float32                `protobuf:"fixed32,4,opt,name=threshold,proto3" json:"threshold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchMemoriesRequest) Reset() {
	*x = SearchMemoriesRequest{}
	mi := &file_marchproxy_waddleai_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMemoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMemoriesRequest) ProtoMessage() {}

func (x *SearchMemoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_marchproxy_waddleai_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMemoriesRequest.ProtoReflect.Descriptor instead.
func (*SearchMemoriesRequest) Descriptor() ([]byte, []int) {
	return file_marchproxy_waddleai_proto_rawDescGZIP(), []int{8}
}

func (x *SearchMemoriesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchMemoriesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SearchMemoriesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchMemoriesRequest) GetThreshold() float32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

type SearchMemoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*MemoryEntry         `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchMemoriesResponse) Reset() {
	*x = SearchMemoriesResponse{}
	mi := &file_marchproxy_waddleai_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMemoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMemoriesResponse) ProtoMessage() {}

func (x *SearchMemoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_marchproxy_waddleai_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMemoriesResponse.ProtoReflect.Descriptor instead.
func (*SearchMemoriesResponse) Descriptor() ([]byte, []int) {
	return file_marchproxy_waddleai_proto_rawDescGZIP(), []int{9}
}

func (x *SearchMemoriesResponse) GetResults() []*MemoryEntry {
	if x != nil {
		return x.Results
	}
	return nil
}

type MemoryEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Similarity    float32                `protobuf:"fixed32,4,opt,name=similarity,proto3" json:"similarity,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryEntry) Reset() {
	*x = MemoryEntry{}
	mi := &file_marchproxy_waddleai_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryEntry) ProtoMessage() {}

func (x *MemoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_marchproxy_waddleai_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryEntry.ProtoReflect.Descriptor instead.
func (*MemoryEntry) Descriptor() ([]byte, []int) {
	return file_marchproxy_waddleai_proto_rawDescGZIP(), []int{10}
}

func (x *MemoryEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MemoryEntry) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MemoryEntry) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *MemoryEntry) GetSimilarity() float32 {
	if x != nil {
		return x.Similarity
	}
	return 0
}

func (x *MemoryEntry) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *MemoryEntry) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type UsageReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ApiKeyId      string                 `protobuf:"bytes,2,opt,name=api_key_id,json=apiKeyId,proto3" json:"api_key_id,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Provider      string                 `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	InputTokens   int32                  `protobuf:"varint,5,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens  int32                  `protobuf:"varint,6,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	TotalTokens   int32                  `protobuf:"varint,7,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	LatencyMs     int32                  `protobuf:"varint,8,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	RequestId     string                 `protobuf:"bytes,9,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Timestamp     string                 `protobuf:"bytes,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,11,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageReport) Reset() {
	*x = UsageReport{}
	mi := &file_marchproxy_waddleai_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageReport) ProtoMessage() {}

func (x *UsageReport) ProtoReflect() protoreflect.Message {
	mi := &file_marchproxy_waddleai_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageReport.ProtoReflect.Descriptor instead.
func (*UsageReport) Descriptor() ([]byte, []int) {
	return file_marchproxy_waddleai_proto_rawDescGZIP(), []int{11}
}

func (x *UsageReport) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UsageReport) GetApiKeyId() string {
	if x != nil {
		return x.ApiKeyId
	}
	return ""
}

func (x *UsageReport) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *UsageReport) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *UsageReport) GetInputTokens() int32 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *UsageReport) GetOutputTokens() int32 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *UsageReport) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

func (x *UsageReport) GetLatencyMs() int32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *UsageReport) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *UsageReport) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *UsageReport) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type UsageAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	QuotaExceeded bool                   `protobuf:"varint,2,opt,name=quota_exceeded,json=quotaExceeded,proto3" json:"quota_exceeded,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsageAck) Reset() {
	*x = UsageAck{}
	mi := &file_marchproxy_waddleai_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsageAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsageAck) ProtoMessage() {}

func (x *UsageAck) ProtoReflect() protoreflect.Message {
	mi := &file_marchproxy_waddleai_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsageAck.ProtoReflect.Descriptor instead.
func (*UsageAck) Descriptor() ([]byte, []int) {
	return file_marchproxy_waddleai_proto_rawDescGZIP(), []int{12}
}

func (x *UsageAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *UsageAck) GetQuotaExceeded() bool {
	if x != nil {
		return x.QuotaExceeded
	}
	return false
}

func (x *UsageAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_marchproxy_waddleai_proto protoreflect.FileDescriptor

const file_marchproxy_waddleai_proto_rawDesc = "" +
	"\n" +
	"\x19marchproxy/waddleai.proto\x12\n" +
	"marchproxy\"\x94\x02\n" +
	"\fRouteRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x1b\n" +
	"\ttool_type\x18\x02 \x01(\tR\btoolType\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x16\n" +
	"\x06region\x18\x05 \x01(\tR\x06region\x12B\n" +
	"\bmetadata\x18\x06 \x03(\v2&.marchproxy.RouteRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbb\x01\n" +
	"\rRouteResponse\x12+\n" +
	"\x11recommended_model\x18\x01 \x01(\tR\x10recommendedModel\x12\x1e\n" +
	"\n" +
	"complexity\x18\x02 \x01(\tR\n" +
	"complexity\x12\x1f\n" +
	"\vtarget_type\x18\x03 \x01(\tR\n" +
	"targetType\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x02R\n" +
	"confidence\x12\x1c\n" +
	"\treasoning\x18\x05 \x01(\tR\treasoning\"\xe8\x01\n" +
	"\x0fSecurityRequest\x12\x1f\n" +
	"\vraw_command\x18\x01 \x01(\tR\n" +
	"rawCommand\x12\x1b\n" +
	"\ttool_type\x18\x02 \x01(\tR\btoolType\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12B\n" +
	"\acontext\x18\x04 \x03(\v2(.marchproxy.SecurityRequest.ContextEntryR\acontext\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa2\x01\n" +
	"\x10SecurityResponse\x12\x12\n" +
	"\x04safe\x18\x01 \x01(\bR\x04safe\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x02 \x01(\x02R\triskScore\x12\x1f\n" +
	"\vthreat_type\x18\x03 \x01(\tR\n" +
	"threatType\x12 \n" +
	"\vexplanation\x18\x04 \x01(\tR\vexplanation\x12\x18\n" +
	"\ablocked\x18\x05 \x01(\bR\ablocked\"\xd3\x02\n" +
	"\x10StoreTurnRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12!\n" +
	"\fuser_message\x18\x03 \x01(\tR\vuserMessage\x12-\n" +
	"\x12assistant_response\x18\x04 \x01(\tR\x11assistantResponse\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\x12\x1a\n" +
	"\bprovider\x18\x06 \x01(\tR\bprovider\x12F\n" +
	"\bmetadata\x18\a \x03(\v2*.marchproxy.StoreTurnRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"-\n" +
	"\x11StoreTurnResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"a\n" +
	"\x11GetContextRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"c\n" +
	"\x12GetContextResponse\x123\n" +
	"\bmemories\x18\x01 \x03(\v2\x17.marchproxy.MemoryEntryR\bmemories\x12\x18\n" +
	"\asummary\x18\x02 \x01(\tR\asummary\"z\n" +
	"\x15SearchMemoriesRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x1c\n" +
	"\tthreshold\x18\x04 \x01(\x02R\tthreshold\"K\n" +
	"\x16SearchMemoriesResponse\x121\n" +
	"\aresults\x18\x01 \x03(\v2\x17.marchproxy.MemoryEntryR\aresults\"\x8a\x02\n" +
	"\vMemoryEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x1e\n" +
	"\n" +
	"similarity\x18\x04 \x01(\x02R\n" +
	"similarity\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12A\n" +
	"\bmetadata\x18\x06 \x03(\v2%.marchproxy.MemoryEntry.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbd\x03\n" +
	"\vUsageReport\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1c\n" +
	"\n" +
	"api_key_id\x18\x02 \x01(\tR\bapiKeyId\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x1a\n" +
	"\bprovider\x18\x04 \x01(\tR\bprovider\x12!\n" +
	"\finput_tokens\x18\x05 \x01(\x05R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x06 \x01(\x05R\foutputTokens\x12!\n" +
	"\ftotal_tokens\x18\a \x01(\x05R\vtotalTokens\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\b \x01(\x05R\tlatencyMs\x12\x1d\n" +
	"\n" +
	"request_id\x18\t \x01(\tR\trequestId\x12\x1c\n" +
	"\ttimestamp\x18\n" +
	" \x01(\tR\ttimestamp\x12A\n" +
	"\bmetadata\x18\v \x03(\v2%.marchproxy.UsageReport.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"g\n" +
	"\bUsageAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12%\n" +
	"\x0equota_exceeded\x18\x02 \x01(\bR\rquotaExceeded\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\xd4\x03\n" +
	"\x0fWaddleAIService\x12D\n" +
	"\rEvaluateRoute\x12\x18.marchproxy.RouteRequest\x1a\x19.marchproxy.RouteResponse\x12M\n" +
	"\x10EvaluateSecurity\x12\x1b.marchproxy.SecurityRequest\x1a\x1c.marchproxy.SecurityResponse\x12H\n" +
	"\tStoreTurn\x12\x1c.marchproxy.StoreTurnRequest\x1a\x1d.marchproxy.StoreTurnResponse\x12K\n" +
	"\n" +
	"GetContext\x12\x1d.marchproxy.GetContextRequest\x1a\x1e.marchproxy.GetContextResponse\x12W\n" +
	"\x0eSearchMemories\x12!.marchproxy.SearchMemoriesRequest\x1a\".marchproxy.SearchMemoriesResponse\x12<\n" +
	"\vReportUsage\x12\x17.marchproxy.UsageReport\x1a\x14.marchproxy.UsageAckB?Z=github.com/penguintech/marchproxy/proto/marchproxy;marchproxyb\x06proto3"

var (
	file_marchproxy_waddleai_proto_rawDescOnce sync.Once
	file_marchproxy_waddleai_proto_rawDescData []byte
)

func file_marchproxy_waddleai_proto_rawDescGZIP() []byte {
	file_marchproxy_waddleai_proto_rawDescOnce.Do(func() {
		file_marchproxy_waddleai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_marchproxy_waddleai_proto_rawDesc), len(file_marchproxy_waddleai_proto_rawDesc)))
	})
	return file_marchproxy_waddleai_proto_rawDescData
}

var file_marchproxy_waddleai_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_marchproxy_waddleai_proto_goTypes = []any{
	(*RouteRequest)(nil),           // 0: marchproxy.RouteRequest
	(*RouteResponse)(nil),          // 1: marchproxy.RouteResponse
	(*SecurityRequest)(nil),        // 2: marchproxy.SecurityRequest
	(*SecurityResponse)(nil),       // 3: marchproxy.SecurityResponse
	(*StoreTurnRequest)(nil),       // 4: marchproxy.StoreTurnRequest
	(*StoreTurnResponse)(nil),      // 5: marchproxy.StoreTurnResponse
	(*GetContextRequest)(nil),      // 6: marchproxy.GetContextRequest
	(*GetContextResponse)(nil),     // 7: marchproxy.GetContextResponse
	(*SearchMemoriesRequest)(nil),  // 8: marchproxy.SearchMemoriesRequest
	(*SearchMemoriesResponse)(nil), // 9: marchproxy.SearchMemoriesResponse
	(*MemoryEntry)(nil),            // 10: marchproxy.MemoryEntry
	(*UsageReport)(nil),            // 11: marchproxy.UsageReport
	(*UsageAck)(nil),               // 12: marchproxy.UsageAck
	nil,                            // 13: marchproxy.RouteRequest.MetadataEntry
	nil,                            // 14: marchproxy.SecurityRequest.ContextEntry
	nil,                            // 15: marchproxy.StoreTurnRequest.MetadataEntry
	nil,                            // 16: marchproxy.MemoryEntry.MetadataEntry
	nil,                            // 17: marchproxy.UsageReport.MetadataEntry
}
var file_marchproxy_waddleai_proto_depIdxs = []int32{
	13, // 0: marchproxy.RouteRequest.metadata:type_name -> marchproxy.RouteRequest.MetadataEntry
	14, // 1: marchproxy.SecurityRequest.context:type_name -> marchproxy.SecurityRequest.ContextEntry
	15, // 2: marchproxy.StoreTurnRequest.metadata:type_name -> marchproxy.StoreTurnRequest.MetadataEntry
	10, // 3: marchproxy.GetContextResponse.memories:type_name -> marchproxy.MemoryEntry
	10, // 4: marchproxy.SearchMemoriesResponse.results:type_name -> marchproxy.MemoryEntry
	16, // 5: marchproxy.MemoryEntry.metadata:type_name -> marchproxy.MemoryEntry.MetadataEntry
	17, // 6: marchproxy.UsageReport.metadata:type_name -> marchproxy.UsageReport.MetadataEntry
	0,  // 7: marchproxy.WaddleAIService.EvaluateRoute:input_type -> marchproxy.RouteRequest
	2,  // 8: marchproxy.WaddleAIService.EvaluateSecurity:input_type -> marchproxy.SecurityRequest
	4,  // 9: marchproxy.WaddleAIService.StoreTurn:input_type -> marchproxy.StoreTurnRequest
	6,  // 10: marchproxy.WaddleAIService.GetContext:input_type -> marchproxy.GetContextRequest
	8,  // 11: marchproxy.WaddleAIService.SearchMemories:input_type -> marchproxy.SearchMemoriesRequest
	11, // 12: marchproxy.WaddleAIService.ReportUsage:input_type -> marchproxy.UsageReport
	1,  // 13: marchproxy.WaddleAIService.EvaluateRoute:output_type -> marchproxy.RouteResponse
	3,  // 14: marchproxy.WaddleAIService.EvaluateSecurity:output_type -> marchproxy.SecurityResponse
	5,  // 15: marchproxy.WaddleAIService.StoreTurn:output_type -> marchproxy.StoreTurnResponse
	7,  // 16: marchproxy.WaddleAIService.GetContext:output_type -> marchproxy.GetContextResponse
	9,  // 17: marchproxy.WaddleAIService.SearchMemories:output_type -> marchproxy.SearchMemoriesResponse
	12, // 18: marchproxy.WaddleAIService.ReportUsage:output_type -> marchproxy.UsageAck
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_marchproxy_waddleai_proto_init() }
func file_marchproxy_waddleai_proto_init() {
	if File_marchproxy_waddleai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_marchproxy_waddleai_proto_rawDesc), len(file_marchproxy_waddleai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_marchproxy_waddleai_proto_goTypes,
		DependencyIndexes: file_marchproxy_waddleai_proto_depIdxs,
		MessageInfos:      file_marchproxy_waddleai_proto_msgTypes,
	}.Build()
	File_marchproxy_waddleai_proto = out.File
	file_marchproxy_waddleai_proto_goTypes = nil
	file_marchproxy_waddleai_proto_depIdxs = nil
}
