// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: marchproxy/waddleai.proto

package marchproxy

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WaddleAIService_EvaluateRoute_FullMethodName    = "/marchproxy.WaddleAIService/EvaluateRoute"
	WaddleAIService_EvaluateSecurity_FullMethodName = "/marchproxy.WaddleAIService/EvaluateSecurity"
	WaddleAIService_StoreTurn_FullMethodName        = "/marchproxy.WaddleAIService/StoreTurn"
	WaddleAIService_GetContext_FullMethodName       = "/marchproxy.WaddleAIService/GetContext"
	WaddleAIService_SearchMemories_FullMethodName   = "/marchproxy.WaddleAIService/SearchMemories"
	WaddleAIService_ReportUsage_FullMethodName      = "/marchproxy.WaddleAIService/ReportUsage"
)

// WaddleAIServiceClient is the client API for WaddleAIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WaddleAIServiceClient interface {
	// Routing: Evaluate prompt complexity, return model recommendation
	EvaluateRoute(ctx context.Context, in *RouteRequest, opts ...grpc.CallOption) (*RouteResponse, error)
	// Security: Evaluate raw tool command for threats
	EvaluateSecurity(ctx context.Context, in *SecurityRequest, opts ...grpc.CallOption) (*SecurityResponse, error)
	// Memory: Store conversation turn
	StoreTurn(ctx context.Context, in *StoreTurnRequest, opts ...grpc.CallOption) (*StoreTurnResponse, error)
	// Memory: Retrieve context for session
	GetContext(ctx context.Context, in *GetContextRequest, opts ...grpc.CallOption) (*GetContextResponse, error)
	// Memory: Search memories
	SearchMemories(ctx context.Context, in *SearchMemoriesRequest, opts ...grpc.CallOption) (*SearchMemoriesResponse, error)
	// Usage: Report token usage per model/user (Premium — license-gated on WaddleAI side)
	ReportUsage(ctx context.Context, in *UsageReport, opts ...grpc.CallOption) (*UsageAck, error)
}

type waddleAIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWaddleAIServiceClient(cc grpc.ClientConnInterface) WaddleAIServiceClient {
	return &waddleAIServiceClient{cc}
}

func (c *waddleAIServiceClient) EvaluateRoute(ctx context.Context, in *RouteRequest, opts ...grpc.CallOption) (*RouteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RouteResponse)
	err := c.cc.Invoke(ctx, WaddleAIService_EvaluateRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *waddleAIServiceClient) EvaluateSecurity(ctx context.Context, in *SecurityRequest, opts ...grpc.CallOption) (*SecurityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SecurityResponse)
	err := c.cc.Invoke(ctx, WaddleAIService_EvaluateSecurity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *waddleAIServiceClient) StoreTurn(ctx context.Context, in *StoreTurnRequest, opts ...grpc.CallOption) (*StoreTurnResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreTurnResponse)
	err := c.cc.Invoke(ctx, WaddleAIService_StoreTurn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *waddleAIServiceClient) GetContext(ctx context.Context, in *GetContextRequest, opts ...grpc.CallOption) (*GetContextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContextResponse)
	err := c.cc.Invoke(ctx, WaddleAIService_GetContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *waddleAIServiceClient) SearchMemories(ctx context.Context, in *SearchMemoriesRequest, opts ...grpc.CallOption) (*SearchMemoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchMemoriesResponse)
	err := c.cc.Invoke(ctx, WaddleAIService_SearchMemories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *waddleAIServiceClient) ReportUsage(ctx context.Context, in *UsageReport, opts ...grpc.CallOption) (*UsageAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UsageAck)
	err := c.cc.Invoke(ctx, WaddleAIService_ReportUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WaddleAIServiceServer is the server API for WaddleAIService service.
// All implementations must embed UnimplementedWaddleAIServiceServer
// for forward compatibility.
type WaddleAIServiceServer interface {
	// Routing: Evaluate prompt complexity, return model recommendation
	EvaluateRoute(context.Context, *RouteRequest) (*RouteResponse, error)
	// Security: Evaluate raw tool command for threats
	EvaluateSecurity(context.Context, *SecurityRequest) (*SecurityResponse, error)
	// Memory: Store conversation turn
	StoreTurn(context.Context, *StoreTurnRequest) (*StoreTurnResponse, error)
	// Memory: Retrieve context for session
	GetContext(context.Context, *GetContextRequest) (*GetContextResponse, error)
	// Memory: Search memories
	SearchMemories(context.Context, *SearchMemoriesRequest) (*SearchMemoriesResponse, error)
	// Usage: Report token usage per model/user (Premium — license-gated on WaddleAI side)
	ReportUsage(context.Context, *UsageReport) (*UsageAck, error)
	mustEmbedUnimplementedWaddleAIServiceServer()
}

// UnimplementedWaddleAIServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWaddleAIServiceServer struct{}

func (UnimplementedWaddleAIServiceServer) EvaluateRoute(context.Context, *RouteRequest) (*RouteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EvaluateRoute not implemented")
}
func (UnimplementedWaddleAIServiceServer) EvaluateSecurity(context.Context, *SecurityRequest) (*SecurityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EvaluateSecurity not implemented")
}
func (UnimplementedWaddleAIServiceServer) StoreTurn(context.Context, *StoreTurnRequest) (*StoreTurnResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StoreTurn not implemented")
}
func (UnimplementedWaddleAIServiceServer) GetContext(context.Context, *GetContextRequest) (*GetContextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContext not implemented")
}
func (UnimplementedWaddleAIServiceServer) SearchMemories(context.Context, *SearchMemoriesRequest) (*SearchMemoriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchMemories not implemented")
}
func (UnimplementedWaddleAIServiceServer) ReportUsage(context.Context, *UsageReport) (*UsageAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportUsage not implemented")
}
func (UnimplementedWaddleAIServiceServer) mustEmbedUnimplementedWaddleAIServiceServer() {}
func (UnimplementedWaddleAIServiceServer) testEmbeddedByValue()                         {}

// UnsafeWaddleAIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WaddleAIServiceServer will
// result in compilation errors.
type UnsafeWaddleAIServiceServer interface {
	mustEmbedUnimplementedWaddleAIServiceServer()
}

func RegisterWaddleAIServiceServer(s grpc.ServiceRegistrar, srv WaddleAIServiceServer) {
	// If the following call panics, it indicates UnimplementedWaddleAIServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WaddleAIService_ServiceDesc, srv)
}

func _WaddleAIService_EvaluateRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WaddleAIServiceServer).EvaluateRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WaddleAIService_EvaluateRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WaddleAIServiceServer).EvaluateRoute(ctx, req.(*RouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WaddleAIService_EvaluateSecurity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecurityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WaddleAIServiceServer).EvaluateSecurity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WaddleAIService_EvaluateSecurity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WaddleAIServiceServer).EvaluateSecurity(ctx, req.(*SecurityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WaddleAIService_StoreTurn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreTurnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WaddleAIServiceServer).StoreTurn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WaddleAIService_StoreTurn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WaddleAIServiceServer).StoreTurn(ctx, req.(*StoreTurnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WaddleAIService_GetContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WaddleAIServiceServer).GetContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WaddleAIService_GetContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WaddleAIServiceServer).GetContext(ctx, req.(*GetContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WaddleAIService_SearchMemories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchMemoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WaddleAIServiceServer).SearchMemories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WaddleAIService_SearchMemories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WaddleAIServiceServer).SearchMemories(ctx, req.(*SearchMemoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WaddleAIService_ReportUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsageReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WaddleAIServiceServer).ReportUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WaddleAIService_ReportUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WaddleAIServiceServer).ReportUsage(ctx, req.(*UsageReport))
	}
	return interceptor(ctx, in, info, handler)
}

// WaddleAIService_ServiceDesc is the grpc.ServiceDesc for WaddleAIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WaddleAIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "marchproxy.WaddleAIService",
	HandlerType: (*WaddleAIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EvaluateRoute",
			Handler:    _WaddleAIService_EvaluateRoute_Handler,
		},
		{
			MethodName: "EvaluateSecurity",
			Handler:    _WaddleAIService_EvaluateSecurity_Handler,
		},
		{
			MethodName: "StoreTurn",
			Handler:    _WaddleAIService_StoreTurn_Handler,
		},
		{
			MethodName: "GetContext",
			Handler:    _WaddleAIService_GetContext_Handler,
		},
		{
			MethodName: "SearchMemories",
			Handler:    _WaddleAIService_SearchMemories_Handler,
		},
		{
			MethodName: "ReportUsage",
			Handler:    _WaddleAIService_ReportUsage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "marchproxy/waddleai.proto",
}
